#!/usr/bin/env bash
# test/agents-md-coexist.test.sh — AGENTS.md is SHARED GROUND. Prove hmd coexists.
#
# WHAT THIS GATES. `hmd init` is not the only tool that writes AGENTS.md. Headroom's
# `headroom learn` writes into AGENTS.md / CLAUDE.md too, and a dev may well run both
# in the same repo, in either order, repeatedly. Two generated-region writers sharing
# one file is a data-loss hazard: whoever renders second can trivially eat the first
# one's section, or weld a marker onto a line it does not own.
#
# The contract this holds:
#   1. hmd APPENDS beside a foreign generated region — never through it.
#   2. Re-running EITHER tool, in EITHER order, any number of times, converges to a
#      fixed point: exactly one of each region, and the file stops changing.
#   3. The user's own prose — every line outside BOTH tools' regions — is byte-identical
#      after every permutation. Asserted with a CHECKSUM, never an eyeball diff: that is
#      how the sibling gates prove it, and it is what caught the real .gitignore
#      data-loss bug (see test/init-gitignore-append.test.sh).
#   4. The UNTERMINATED-FILE hazard is exercised in BOTH directions:
#        · hmd inheriting a foreign file whose last line has no newline -> must not weld.
#        · hmd's OWN output must always end in a newline, so the NEXT tool's bare `>>`
#          cannot weld its marker onto hmd's END marker. That is hmd's half of the
#          coexistence contract and the exact shape of the .gitignore bug.
#
# ── THE FOREIGN REGION IS A REPRESENTATIVE FIXTURE, NOT HEADROOM'S REAL FORMAT ──
# Headroom is NOT installed here and is deliberately NOT installed by this gate
# (depend, don't clone — it is not a dependency of Heimdall at all). Its real marker
# text could not be established from any material in this repo: the only mentions are
# two out-of-scope lines in docs/archive/.../heimdall-telemetry-design.md:310,313, and
# neither documents a marker shape. So `HR_BEGIN`/`HR_END` below are a CLEARLY LABELLED
# REPRESENTATIVE fixture, modelled on the HTML-comment BEGIN/END convention this repo
# already uses for generated regions (HEIMDALL:VERSION in README.md, HEIMDALL:AGENTS in
# AGENTS.md). They are NOT a claim about Headroom's actual output.
#
# That is sound, and here is why the proof does not depend on guessing their format:
# hmd's guarantee is not "I understand Headroom" — it is "every line outside MY fence is
# passed through untouched". That is a UNIVERSAL property over foreign content, so a
# fixture that is merely *shaped like* a generated region exercises it exactly as a real
# one would. If Headroom's true markers differ, only the fixture strings change; every
# assertion below still holds verbatim.
#
# `headroom_learn` is likewise a STAND-IN writer — a well-behaved generated-region
# renderer written here, not Headroom's code. `headroom_learn_naive` is its deliberately
# unguarded twin (a bare `>>`, no final-newline check) used to model a second tool that
# does NOT guard the weld hazard; it exists to prove HMD holds up its own end.
#
# FALSIFIABILITY. `--self-test` mutates a COPY of bin/heimdall-init to reintroduce three
# coexistence failure modes — clobbering the foreign region, welding onto an unterminated
# foreign file, and emitting an unterminated file for the next tool to weld onto — and
# asserts THIS script reports RED for each. A gate that cannot fail is decoration. The
# mutants are discarded; bin/heimdall-init is never modified.
#
# HERMETIC. Every repo is a throwaway temp git repo, HOME is redirected, and the egress
# default is pinned at a dead port, so nothing touches the real ~/.heimdall (live team
# secret + PKI) and no beat can reach a live control plane. Local artifacts only.
#
# EXIT: 0 = every proof holds; 1 = any FAIL.
set -uo pipefail

SELF="${BASH_SOURCE[0]}"
SELF_DIR="$(cd "$(dirname "$SELF")" && pwd)"
REPO="$(cd "$SELF_DIR/.." && pwd)"
BIN="$REPO/bin"

# The bin under test. `--self-test` re-runs this script with a MUTATED copy pointed here;
# every normal run gates the real one.
INIT_BIN="${HMD_INIT_BIN:-$BIN/heimdall-init}"

# DEFAULT-ON egress guard: init generates a post-commit hook that shells the real presence
# beat. Pin the baked-in default at a dead port so a fresh, undecided HOME can never
# resolve the prod control plane.
. "$REPO/test/lib/net-default-guard.sh"

[ -x "$INIT_BIN" ] || { echo "FATAL: missing/!exec $INIT_BIN" >&2; exit 2; }
command -v git >/dev/null 2>&1 || { echo "FATAL: git not found" >&2; exit 2; }
command -v shasum >/dev/null 2>&1 || { echo "FATAL: shasum not found" >&2; exit 2; }

# hmd's fence, pinned here rather than read out of the implementation: a test that derives
# the contract from the code under test cannot detect the contract changing.
AG_BEGIN='<!-- HEIMDALL:AGENTS:BEGIN — generated by `hmd init`; edits inside this fence are overwritten on re-init -->'
AG_END='<!-- HEIMDALL:AGENTS:END -->'

# The foreign region. REPRESENTATIVE FIXTURE — see the header. Not Headroom's real markers.
HR_BEGIN='<!-- HEADROOM:BEGIN generated by `headroom learn` — do not edit by hand -->'
HR_END='<!-- HEADROOM:END -->'

PASS=0; FAIL=0
ok()  { PASS=$((PASS+1)); printf "  \033[32mPASS\033[0m %s\n" "$1"; }
bad() { FAIL=$((FAIL+1)); printf "  \033[31mFAIL\033[0m %s\n" "$1"; [ -n "${2:-}" ] && printf '        %s\n' "$2" >&2; return 0; }

WORK="$(mktemp -d "${TMPDIR:-/tmp}/hmd-agents-coexist.XXXXXX")"
cleanup() { rm -rf "$WORK" 2>/dev/null || true; }
trap cleanup EXIT
export HOME="$WORK/home"; mkdir -p "$HOME/.heimdall"
export HEIMDALL_NO_TEAM_AUTOSHARE=1

# ══════════════════════════════════════════════════════════════════════════════
# --self-test — PROVE THIS GATE CAN FAIL.
# ══════════════════════════════════════════════════════════════════════════════
stage_mutant() {
  local name="$1"; shift
  local dir="$WORK/mutant-$name" e expr
  mkdir -p "$dir"
  for e in "$BIN"/*; do ln -sf "$e" "$dir/$(basename "$e")"; done
  rm -f "$dir/heimdall-init"
  cp "$BIN/heimdall-init" "$dir/heimdall-init"
  for expr in "$@"; do
    perl -0777 -i -pe "$expr" "$dir/heimdall-init" || return 1
  done
  chmod +x "$dir/heimdall-init"
  if cmp -s "$BIN/heimdall-init" "$dir/heimdall-init"; then
    echo "  ✗ SELF-TEST BROKEN: mutation '$name' changed nothing — the mutant is the original" >&2
    return 1
  fi
  bash -n "$dir/heimdall-init" 2>/dev/null || { echo "  ✗ SELF-TEST BROKEN: mutation '$name' produced unparseable bash" >&2; return 1; }
  printf '%s\n' "$dir/heimdall-init"
}

assert_red() {
  local label="$1" mutant="$2" out="$WORK/selftest-$3.out"
  echo "  · mutation: $label"
  if env HMD_INIT_BIN="$mutant" perl -e 'alarm 400; exec @ARGV' -- bash "$SELF" > "$out" 2>&1; then
    echo "  ✗ SELF-TEST FAILED: the gate stayed GREEN under '$label' — it is decoration, not a gate" >&2
    sed -n '$p' "$out" >&2
    return 1
  fi
  printf '    gate went RED as required → %s\n' "$(grep -c 'FAIL' "$out" | tr -d ' ') FAIL line(s):"
  grep 'FAIL' "$out" | sed 's/^/    /'
  return 0
}

if [ "${1:-}" = "--self-test" ]; then
  echo "agents-md-coexist --self-test: proving the gate goes RED when coexistence breaks"

  # M1 — CLOBBER THE NEIGHBOUR. The append branch truncates instead of appending, so a
  # repo's AGENTS.md — Headroom's section and the dev's own prose with it — is destroyed.
  M1="$(stage_mutant clobber 's/cat "\$new" >> "\$tmp"/cat "\$new" > "\$tmp"/')" || exit 2
  assert_red "append '>>' weakened to '>' → the FOREIGN region is CLOBBERED" "$M1" clobber || exit 1

  # M2 — WELD ONTO THE NEIGHBOUR. Drop the restore-the-missing-final-newline guard, so
  # appending to an unterminated foreign file fuses hmd's BEGIN marker onto Headroom's
  # last line. Both markers stop being markers. This is the .gitignore bug, in AGENTS.md.
  M2="$(stage_mutant weld 's/\[ "\$last" = "0a" \] \|\| printf .\\n. >> "\$tmp"/true/')" || exit 2
  assert_red "final-newline guard removed → hmd WELDS its marker onto the foreign last line" "$M2" weld || exit 1

  # M3 — HAND THE NEXT TOOL A LANDMINE. hmd's own block stops ending in a newline, so the
  # NEXT tool's bare `>>` welds its marker onto hmd's END marker and breaks hmd's fence.
  M3="$(stage_mutant unterminated 's/printf .%s\\n. "\$AG_END"/printf \x27%s\x27 "\$AG_END"/')" || exit 2
  assert_red "hmd emits an UNTERMINATED file → the next tool welds onto hmd's END marker" "$M3" unterminated || exit 1

  echo
  echo "  ✓ all three coexistence failure modes are caught — the gate is falsifiable"
  exit 0
fi

# ── helpers ───────────────────────────────────────────────────────────────────
newrepo() { mkdir -p "$1"; git -C "$1" init -q; git -C "$1" config user.email dev@example.com; git -C "$1" config user.name Dev; }

# run init inside a repo. Alarm-bounded: macOS has no timeout(1), and a hung init must
# fail the gate rather than hang CI forever.
runinit() { local r="$1"; shift; ( cd "$r" && perl -e 'alarm 90; exec @ARGV' -- "$INIT_BIN" "$@" ) >/dev/null 2>&1; }

sum_file() { shasum < "$1" | awk '{print $1}'; }

# THE assertion behind "the user's prose survived": a checksum of every line outside
# BOTH tools' regions, markers excluded. Either region's body may change freely; this
# may not. An empty byte-diff here is the falsifier the whole file is built around.
sum_outside_both() {
  awk -v hb="$AG_BEGIN" -v he="$AG_END" -v fb="$HR_BEGIN" -v fe="$HR_END" '
    $0 == hb { inh = 1; next }
    $0 == he { inh = 0; next }
    $0 == fb { inf = 1; next }
    $0 == fe { inf = 0; next }
    (!inh && !inf) { print }
  ' "$1" | shasum | awk '{print $1}'
}

# Checksum the BODY of one named region — proves a tool did not reach inside a region
# it does not own.
sum_region() {
  awk -v b="$2" -v e="$3" '
    $0 == b { inb = 1; next }
    $0 == e { inb = 0; next }
    inb     { print }
  ' "$1" | shasum | awk '{print $1}'
}

# Raw byte-prefix checksum — the strictest form of "byte-identical", used where the prior
# file already ended in a newline and must therefore be an exact prefix.
sum_prefix() { head -c "$2" "$1" | shasum | awk '{print $1}'; }

count_line() { grep -Fxc "$1" "$2" 2>/dev/null || true; }

# last byte of a file, as hex. "0a" = properly newline-terminated.
last_byte() { tail -c 1 "$1" | od -An -tx1 | tr -d '[:space:]'; }

# ── the foreign tool, STAND-IN ────────────────────────────────────────────────
# A well-behaved generated-region writer: appends its region if absent, re-renders it in
# place if present, and never touches a line outside it. Modelled on the same convention
# hmd uses — NOT Headroom's code. `$1` = repo, `$2` = a body marker so a re-learn can be
# told apart from the first learn.
headroom_render() {
  printf '%s\n' "$HR_BEGIN"
  printf '\n## Project memory (learned)\n\n'
  printf -- '- build: `make test` (learned %s)\n' "$1"
  printf -- '- entrypoints live under `cmd/`\n\n'
  printf '%s\n' "$HR_END"
}

headroom_learn() {
  # NOTE: one `local` per name that another references — bash expands every word on the
  # `local` line BEFORE any of them is bound, so `local a=$1 b="$a/x"` reads an unset $a.
  local repo="$1"
  local gen="${2:-1}"
  local f="$repo/AGENTS.md"
  local new tmp
  new="$(mktemp "$WORK/hr-new.XXXXXX")"; tmp="$(mktemp "$WORK/hr-tmp.XXXXXX")"
  headroom_render "$gen" > "$new"
  if [ ! -f "$f" ]; then
    cat "$new" > "$tmp"
  elif grep -Fqx "$HR_BEGIN" "$f" 2>/dev/null; then
    awk -v begin="$HR_BEGIN" -v end="$HR_END" -v blockfile="$new" '
      $0 == begin { inblock = 1
                    if (!emitted) { while ((getline line < blockfile) > 0) print line; close(blockfile); emitted = 1 }
                    next }
      $0 == end   { inblock = 0; next }
      !inblock    { print }
    ' "$f" > "$tmp"
  else
    cat "$f" > "$tmp"
    # the same weld guard hmd applies — a well-behaved writer restores a missing newline
    if [ -s "$tmp" ] && [ "$(last_byte "$tmp")" != "0a" ]; then printf '\n' >> "$tmp"; fi
    cat "$new" >> "$tmp"
  fi
  cat "$tmp" > "$f"
  rm -f "$new" "$tmp"
}

# The UNGUARDED twin: a bare `>>` with no final-newline check. Models a second tool that
# does NOT guard the weld hazard. Used ONLY to prove hmd never hands one a file to weld on.
headroom_learn_naive() {
  local repo="$1" gen="${2:-1}"
  headroom_render "$gen" >> "$repo/AGENTS.md"
}

# The dev's own AGENTS.md, with the foreign region already in it and their own prose on
# BOTH sides of it — so a writer that appends past the end and one that overwrites from
# the top are both caught.
write_fixture() {
  local f="$1" gen="${2:-1}"
  {
    printf '# Acme service\n\nHouse rules for agents working here.\n\n'
    printf -- '- Run `make test` before every commit.\n'
    printf -- '- Never edit `vendor/`.\n\n'
    headroom_render "$gen"
    printf '\n## Layout\n\n`cmd/` is entrypoints, `internal/` is everything else.\n'
  } > "$f"
}

echo "════════════════════════════════════════════════════════════════"
echo "AGENTS.md coexistence — hmd beside a FOREIGN generated region"
echo "  foreign fixture: REPRESENTATIVE (Headroom not installed; see header)"
echo "════════════════════════════════════════════════════════════════"

# ══════════════════════════════════════════════════════════════════════════════
# 1. APPEND BESIDE — hmd lands next to a foreign region, never through it
# ══════════════════════════════════════════════════════════════════════════════
R1="$WORK/r1"; newrepo "$R1"
A1="$R1/AGENTS.md"
write_fixture "$A1"
PRIOR="$WORK/prior.md"; cp "$A1" "$PRIOR"
PRIOR_BYTES="$(wc -c < "$PRIOR" | tr -d ' ')"
PRIOR_SUM="$(sum_file "$PRIOR")"
PRIOR_OUTSIDE="$(sum_outside_both "$PRIOR")"
PRIOR_HRBODY="$(sum_region "$PRIOR" "$HR_BEGIN" "$HR_END")"

runinit "$R1"
[ "$(count_line "$AG_BEGIN" "$A1")" = "1" ] && [ "$(count_line "$AG_END" "$A1")" = "1" ] \
  && ok "1a hmd's fence was appended exactly once beside the foreign region" \
  || bad "1a hmd fence count wrong" "begin=$(count_line "$AG_BEGIN" "$A1") end=$(count_line "$AG_END" "$A1")"
[ "$(count_line "$HR_BEGIN" "$A1")" = "1" ] && [ "$(count_line "$HR_END" "$A1")" = "1" ] \
  && ok "1b the FOREIGN region is still present, exactly once (hmd did not eat it)" \
  || bad "1b the foreign region was damaged" "begin=$(count_line "$HR_BEGIN" "$A1") end=$(count_line "$HR_END" "$A1")"
GOT_HRBODY="$(sum_region "$A1" "$HR_BEGIN" "$HR_END")"
[ "$GOT_HRBODY" = "$PRIOR_HRBODY" ] \
  && ok "1c the foreign region's BODY is byte-identical (sha1 $PRIOR_HRBODY) — hmd did not reach inside a region it does not own" \
  || bad "1c hmd modified content INSIDE the foreign region" "want $PRIOR_HRBODY got $GOT_HRBODY"
# THE falsifier: the byte-diff outside BOTH tools' sections must be empty.
GOT_OUTSIDE="$(sum_outside_both "$A1")"
[ "$GOT_OUTSIDE" = "$PRIOR_OUTSIDE" ] \
  && ok "1d the dev's own prose is byte-identical OUTSIDE BOTH regions (sha1 $PRIOR_OUTSIDE)" \
  || bad "1d content changed outside both regions" "want $PRIOR_OUTSIDE got $GOT_OUTSIDE"
# And the strictest form: the whole prior file survives as an exact byte PREFIX.
GOT_PREFIX="$(sum_prefix "$A1" "$PRIOR_BYTES")"
[ "$GOT_PREFIX" = "$PRIOR_SUM" ] \
  && ok "1e the pre-existing file survives as an exact byte prefix (first $PRIOR_BYTES bytes, sha1 $PRIOR_SUM)" \
  || bad "1e the first $PRIOR_BYTES bytes are not the original file" "want $PRIOR_SUM got $GOT_PREFIX"

# ══════════════════════════════════════════════════════════════════════════════
# 2. ORDER A — headroom → hmd → headroom → hmd. Converges; nobody loses a byte.
# ══════════════════════════════════════════════════════════════════════════════
R2="$WORK/r2"; newrepo "$R2"
A2="$R2/AGENTS.md"
printf '# Beta service\n\nOur own notes live here and belong to us.\n' > "$A2"
BASE_OUTSIDE="$(sum_outside_both "$A2")"

headroom_learn "$R2" 1
runinit "$R2"
ORD_A_R1="$(sum_file "$A2")"
headroom_learn "$R2" 1
runinit "$R2"
ORD_A_R2="$(sum_file "$A2")"
headroom_learn "$R2" 1
runinit "$R2"
ORD_A_R3="$(sum_file "$A2")"

[ "$(count_line "$AG_BEGIN" "$A2")" = "1" ] && [ "$(count_line "$HR_BEGIN" "$A2")" = "1" ] \
  && ok "2a order A (headroom→hmd ×3): exactly ONE of each region — neither tool duplicated" \
  || bad "2a a region duplicated under order A" "hmd=$(count_line "$AG_BEGIN" "$A2") foreign=$(count_line "$HR_BEGIN" "$A2")"
[ "$ORD_A_R1" = "$ORD_A_R2" ] && [ "$ORD_A_R2" = "$ORD_A_R3" ] \
  && ok "2b order A reaches a FIXED POINT — the file does not drift one byte across rounds (sha1 $ORD_A_R1)" \
  || bad "2b order A drifts across rounds" "r1=$ORD_A_R1 r2=$ORD_A_R2 r3=$ORD_A_R3"
[ "$(sum_outside_both "$A2")" = "$BASE_OUTSIDE" ] \
  && ok "2c order A: the dev's prose is byte-identical after 6 interleaved writes (sha1 $BASE_OUTSIDE)" \
  || bad "2c order A destroyed content outside both regions" "want $BASE_OUTSIDE got $(sum_outside_both "$A2")"

# The foreign tool RE-LEARNS with new content; hmd re-inits after. hmd must carry the
# NEW foreign body through untouched — passing through a *stale* copy is also a loss.
headroom_learn "$R2" 2
RELEARNED="$(sum_region "$A2" "$HR_BEGIN" "$HR_END")"
runinit "$R2"
[ "$(sum_region "$A2" "$HR_BEGIN" "$HR_END")" = "$RELEARNED" ] \
  && ok "2d a foreign RE-LEARN survives the next hmd init (the new body, not a stale one)" \
  || bad "2d hmd did not preserve the re-learned foreign body"
grep -Fq 'learned 2' "$A2" && ok "2e the re-learned marker text is present after hmd re-init" \
  || bad "2e the re-learned foreign content was lost"

# ══════════════════════════════════════════════════════════════════════════════
# 3. ORDER B — hmd → headroom → hmd → headroom. Same guarantees, reversed.
# ══════════════════════════════════════════════════════════════════════════════
R3="$WORK/r3"; newrepo "$R3"
A3="$R3/AGENTS.md"
printf '# Gamma service\n\nPrior art the repo owns.\n' > "$A3"
B3_OUTSIDE="$(sum_outside_both "$A3")"

runinit "$R3"; headroom_learn "$R3" 1
ORD_B_R1="$(sum_file "$A3")"
runinit "$R3"; headroom_learn "$R3" 1
ORD_B_R2="$(sum_file "$A3")"
runinit "$R3"; headroom_learn "$R3" 1
ORD_B_R3="$(sum_file "$A3")"

[ "$(count_line "$AG_BEGIN" "$A3")" = "1" ] && [ "$(count_line "$HR_BEGIN" "$A3")" = "1" ] \
  && ok "3a order B (hmd→headroom ×3): exactly ONE of each region" \
  || bad "3a a region duplicated under order B" "hmd=$(count_line "$AG_BEGIN" "$A3") foreign=$(count_line "$HR_BEGIN" "$A3")"
[ "$ORD_B_R1" = "$ORD_B_R2" ] && [ "$ORD_B_R2" = "$ORD_B_R3" ] \
  && ok "3b order B reaches a FIXED POINT — no drift across rounds (sha1 $ORD_B_R1)" \
  || bad "3b order B drifts across rounds" "r1=$ORD_B_R1 r2=$ORD_B_R2 r3=$ORD_B_R3"
[ "$(sum_outside_both "$A3")" = "$B3_OUTSIDE" ] \
  && ok "3c order B: the dev's prose is byte-identical after 6 interleaved writes (sha1 $B3_OUTSIDE)" \
  || bad "3c order B destroyed content outside both regions" "want $B3_OUTSIDE got $(sum_outside_both "$A3")"
grep -Fq 'Gates are external and falsifiable — satisfying the oracle is the only path.' "$A3" \
  && ok "3d hmd's load-bearing line survives the foreign tool writing last" \
  || bad "3d hmd's block was damaged by the foreign tool writing after it"

# ══════════════════════════════════════════════════════════════════════════════
# 4. UNTERMINATED, DIRECTION 1 — hmd inherits a foreign file with no final newline
# ══════════════════════════════════════════════════════════════════════════════
# A file whose last line has no newline is ordinary — `printf 'x' > f` makes one. A bare
# `>>` onto it fuses two lines into one and BOTH stop being what they were.
R4="$WORK/r4"; newrepo "$R4"
A4="$R4/AGENTS.md"
{ printf '# Delta service\n\nOurs.\n\n'; headroom_render 1; } > "$A4"
# strip the trailing newline — the foreign tool's END marker is now the unterminated last line
perl -0777 -i -pe 's/\n\z//' "$A4"
[ "$(last_byte "$A4")" != "0a" ] || bad "4 setup failed — the fixture is still newline-terminated"
U4_OUTSIDE="$(sum_outside_both "$A4")"

runinit "$R4"; RC4=$?
[ "$RC4" = 0 ] && ok "4a init exits 0 on an unterminated foreign AGENTS.md" || bad "4a init exited $RC4"
[ "$(count_line "$HR_END" "$A4")" = "1" ] \
  && ok "4b the foreign END marker survives as its OWN whole line — no weld" \
  || bad "4b hmd WELDED onto the foreign last line" "$(grep -c "HEADROOM:END" "$A4") occurrence(s), none whole-line"
[ "$(count_line "$AG_BEGIN" "$A4")" = "1" ] \
  && ok "4c hmd's BEGIN marker landed as its own whole line (still a marker)" \
  || bad "4c hmd's BEGIN marker was welded mid-line and is no longer a marker"
[ "$(sum_outside_both "$A4")" = "$U4_OUTSIDE" ] \
  && ok "4d the dev's prose is byte-identical after the unterminated append (sha1 $U4_OUTSIDE)" \
  || bad "4d the unterminated append damaged content outside both regions"
grep -Fq '# Delta service' "$A4" && ok "4e the dev's own heading survived the unterminated append" \
  || bad "4e the dev's own content was lost"

# ══════════════════════════════════════════════════════════════════════════════
# 5. UNTERMINATED, DIRECTION 2 — hmd must never HAND the next tool a file to weld on
# ══════════════════════════════════════════════════════════════════════════════
# hmd's half of the contract. If hmd's output does not end in a newline, the next tool's
# bare `>>` fuses its BEGIN marker onto hmd's END marker: hmd's own fence breaks, and on
# the following init the unclosed-fence refusal kicks in and hmd stops updating at all.
R5="$WORK/r5"; newrepo "$R5"
A5="$R5/AGENTS.md"
printf '# Epsilon service\n\nOurs, and it stays ours.\n' > "$A5"
E5_OUTSIDE="$(sum_outside_both "$A5")"

runinit "$R5"
[ "$(last_byte "$A5")" = "0a" ] \
  && ok "5a hmd's output ALWAYS ends in a newline — the next tool has nothing to weld onto" \
  || bad "5a hmd left AGENTS.md UNTERMINATED — a bare '>>' from any other tool will weld" "last byte = $(last_byte "$A5")"

# Now let the UNGUARDED tool append. With 5a holding, its marker must land whole-line.
headroom_learn_naive "$R5" 1
[ "$(count_line "$AG_END" "$A5")" = "1" ] \
  && ok "5b hmd's END marker survives an UNGUARDED bare-'>>' append from another tool" \
  || bad "5b an unguarded append welded onto hmd's END marker — hmd's fence is broken"
[ "$(count_line "$HR_BEGIN" "$A5")" = "1" ] \
  && ok "5c the unguarded tool's own marker landed as a whole line" \
  || bad "5c the unguarded tool's marker was welded"

# And hmd must still be able to re-render afterwards — a broken fence would make init
# refuse (unclosed fence) or duplicate. Neither is acceptable.
runinit "$R5"
[ "$(count_line "$AG_BEGIN" "$A5")" = "1" ] && [ "$(count_line "$HR_BEGIN" "$A5")" = "1" ] \
  && ok "5d hmd re-renders cleanly after the unguarded append — still one of each region" \
  || bad "5d hmd could not re-render after an unguarded foreign append" "hmd=$(count_line "$AG_BEGIN" "$A5") foreign=$(count_line "$HR_BEGIN" "$A5")"
[ "$(sum_outside_both "$A5")" = "$E5_OUTSIDE" ] \
  && ok "5e the dev's prose is byte-identical through the whole unguarded round trip (sha1 $E5_OUTSIDE)" \
  || bad "5e the unguarded round trip damaged content outside both regions"

# ══════════════════════════════════════════════════════════════════════════════
# 6. --agents-only coexists too (the re-render path, no hooks, no git config)
# ══════════════════════════════════════════════════════════════════════════════
R6="$WORK/r6"; newrepo "$R6"
A6="$R6/AGENTS.md"
write_fixture "$A6"
S6_OUTSIDE="$(sum_outside_both "$A6")"
S6_HRBODY="$(sum_region "$A6" "$HR_BEGIN" "$HR_END")"
( cd "$R6" && perl -e 'alarm 60; exec @ARGV' -- "$INIT_BIN" --agents-only ) >/dev/null 2>&1
( cd "$R6" && perl -e 'alarm 60; exec @ARGV' -- "$INIT_BIN" --agents-only ) >/dev/null 2>&1
[ "$(count_line "$AG_BEGIN" "$A6")" = "1" ] && [ "$(count_line "$HR_BEGIN" "$A6")" = "1" ] \
  && ok "6a --agents-only ×2 beside a foreign region: one of each, no duplication" \
  || bad "6a --agents-only duplicated a region"
[ "$(sum_region "$A6" "$HR_BEGIN" "$HR_END")" = "$S6_HRBODY" ] \
  && ok "6b --agents-only left the foreign region's body byte-identical" \
  || bad "6b --agents-only modified the foreign region"
[ "$(sum_outside_both "$A6")" = "$S6_OUTSIDE" ] \
  && ok "6c --agents-only left the dev's prose byte-identical (sha1 $S6_OUTSIDE)" \
  || bad "6c --agents-only damaged content outside both regions"

# ══════════════════════════════════════════════════════════════════════════════
# 7. the bin parses clean
# ══════════════════════════════════════════════════════════════════════════════
bash -n "$INIT_BIN" 2>/dev/null && ok "7 bin/heimdall-init passes bash -n" || bad "7 bin/heimdall-init has a syntax error"

echo
printf "  agents-md-coexist: %d passed, %d failed\n" "$PASS" "$FAIL"
[ "$FAIL" -eq 0 ] || exit 1
