#!/usr/bin/env bash
# test/agents-md-injection.test.sh — the AGENTS.md injection contract.
#
# WHAT THIS GATES. AGENTS.md is the one file Cursor, Codex, Gemini CLI and Claude
# Code all read at session start, so `hmd init` writes ONE fenced region there and
# the whole field becomes Heimdall-aware with zero adapters. The contract:
#   1. No AGENTS.md   -> created, with exactly one fenced block.
#   2. An AGENTS.md   -> the block is APPENDED and the prior content survives
#                        BYTE FOR BYTE. Asserted with a checksum of the non-fenced
#                        regions and a raw byte-prefix checksum, never an eyeball diff.
#   3. Re-init        -> idempotent. Exactly one block, and the file does not drift
#                        by a single byte across repeated runs.
#   4. The fence line -> an edit INSIDE the fence is overwritten on re-init (that is
#                        the advertised contract); an edit OUTSIDE it survives.
#   5. An UNCLOSED fence (BEGIN with no END) is REFUSED, not re-rendered — the region
#      would otherwise run to EOF and swallow lines Heimdall does not own.
#
# FALSIFIABILITY. `--self-test` mutates a COPY of bin/heimdall-init to reintroduce the
# two failure modes this file exists to catch — a DUPLICATING fence and a CLOBBERED
# file — and asserts THIS script reports RED for each. A gate that cannot fail is
# decoration. The mutants are discarded; bin/heimdall-init is never modified.
#
# HERMETIC. Every repo is a throwaway temp git repo, HOME is redirected, and the
# egress default is pinned at a dead port, so nothing touches the real ~/.heimdall
# and no beat can reach a live control plane. Local artifacts only.
#
# EXIT: 0 = every proof holds; 1 = any FAIL.
set -uo pipefail

SELF="${BASH_SOURCE[0]}"
SELF_DIR="$(cd "$(dirname "$SELF")" && pwd)"
REPO="$(cd "$SELF_DIR/.." && pwd)"
BIN="$REPO/bin"

# The bin under test. `--self-test` re-runs this script with a MUTATED copy pointed
# at here; every normal run gates the real one.
INIT_BIN="${HMD_INIT_BIN:-$BIN/heimdall-init}"

# DEFAULT-ON egress guard: init generates a post-commit hook that shells the real
# presence beat. Pin the baked-in default at a dead port so a fresh, undecided HOME
# can never resolve the prod control plane.
. "$REPO/test/lib/net-default-guard.sh"

[ -x "$INIT_BIN" ] || { echo "FATAL: missing/!exec $INIT_BIN" >&2; exit 2; }
command -v git >/dev/null 2>&1 || { echo "FATAL: git not found" >&2; exit 2; }
command -v shasum >/dev/null 2>&1 || { echo "FATAL: shasum not found" >&2; exit 2; }

# The fence, pinned here rather than read out of the implementation: a test that
# derives the contract from the code under test cannot detect the contract changing.
AG_BEGIN='<!-- HEIMDALL:AGENTS:BEGIN — generated by `hmd init`; edits inside this fence are overwritten on re-init -->'
AG_END='<!-- HEIMDALL:AGENTS:END -->'

PASS=0; FAIL=0
ok()  { PASS=$((PASS+1)); printf "  \033[32mPASS\033[0m %s\n" "$1"; }
bad() { FAIL=$((FAIL+1)); printf "  \033[31mFAIL\033[0m %s\n" "$1"; [ -n "${2:-}" ] && printf '        %s\n' "$2" >&2; return 0; }

WORK="$(mktemp -d "${TMPDIR:-/tmp}/hmd-agents-md.XXXXXX")"
cleanup() { rm -rf "$WORK" 2>/dev/null || true; }
trap cleanup EXIT
export HOME="$WORK/home"; mkdir -p "$HOME/.heimdall"
export HEIMDALL_NO_TEAM_AUTOSHARE=1

# ══════════════════════════════════════════════════════════════════════════════
# --self-test — PROVE THIS GATE CAN FAIL.
#
# Reintroduces the two failure modes this file exists to catch, each in a COPY of
# bin/heimdall-init, and asserts the gate reports RED for both. bin/heimdall-init is
# never touched: the copy lives in a temp dir alongside SYMLINKS to the real bin, so
# the mutant resolves its siblings (gate-run, presence, lib/) exactly as the real one
# does. A mutation that does not change the file is itself a failure — a self-test
# that silently ran the unmutated bin would be the false green it exists to prevent.
# ══════════════════════════════════════════════════════════════════════════════
stage_mutant() {
  local name="$1"; shift
  local dir="$WORK/mutant-$name" e expr
  mkdir -p "$dir"
  for e in "$BIN"/*; do ln -sf "$e" "$dir/$(basename "$e")"; done
  rm -f "$dir/heimdall-init"
  cp "$BIN/heimdall-init" "$dir/heimdall-init"
  for expr in "$@"; do
    perl -0777 -i -pe "$expr" "$dir/heimdall-init" || return 1
  done
  chmod +x "$dir/heimdall-init"
  if cmp -s "$BIN/heimdall-init" "$dir/heimdall-init"; then
    echo "  ✗ SELF-TEST BROKEN: mutation '$name' changed nothing — the mutant is the original" >&2
    return 1
  fi
  bash -n "$dir/heimdall-init" 2>/dev/null || { echo "  ✗ SELF-TEST BROKEN: mutation '$name' produced unparseable bash" >&2; return 1; }
  printf '%s\n' "$dir/heimdall-init"
}

assert_red() {
  local label="$1" mutant="$2" out="$WORK/selftest-$3.out"
  echo "  · mutation: $label"
  if env HMD_INIT_BIN="$mutant" perl -e 'alarm 400; exec @ARGV' -- bash "$SELF" > "$out" 2>&1; then
    echo "  ✗ SELF-TEST FAILED: the gate stayed GREEN under '$label' — it is decoration, not a gate" >&2
    sed -n '$p' "$out" >&2
    return 1
  fi
  printf '    gate went RED as required → %s\n' "$(grep -c 'FAIL' "$out" | tr -d ' ') FAIL line(s):"
  grep 'FAIL' "$out" | sed 's/^/    /'
  return 0
}

if [ "${1:-}" = "--self-test" ]; then
  echo "agents-md-injection --self-test: proving the gate goes RED when fence handling breaks"
  # M1 — DUPLICATION. Blind the fence detection so an already-fenced file takes the
  # append path, and delete the corrupt-file guard that would otherwise refuse the
  # write. Every re-init then stacks another block.
  M1="$(stage_mutant duplicate \
        's/elif grep -Fqx "\$AG_BEGIN" "\$AGENTS_MD" 2>\/dev\/null; then/elif false; then/' \
        's/  # A render that lost the fence.*?\n  fi\n//s')" || exit 2
  assert_red "re-render disabled + corrupt-file guard removed → the block DUPLICATES" "$M1" duplicate || exit 1

  # M2 — CLOBBER. One character: the append branch truncates the caller's file instead
  # of appending to it, so a repo's own AGENTS.md is destroyed.
  M2="$(stage_mutant clobber 's/cat "\$new" >> "\$tmp"/cat "\$new" > "\$tmp"/')" || exit 2
  assert_red "append '>>' weakened to '>' → a pre-existing AGENTS.md is CLOBBERED" "$M2" clobber || exit 1

  echo
  echo "  ✓ both failure modes are caught — the gate is falsifiable"
  exit 0
fi

# ── helpers ───────────────────────────────────────────────────────────────────
newrepo() { mkdir -p "$1"; git -C "$1" init -q; git -C "$1" config user.email dev@example.com; git -C "$1" config user.name Dev; }

# run init inside a repo. Alarm-bounded: macOS has no timeout(1), and a hung init
# must fail the gate rather than hang CI forever.
runinit() { local r="$1"; shift; ( cd "$r" && perl -e 'alarm 90; exec @ARGV' -- "$INIT_BIN" "$@" ) >/dev/null 2>&1; }

sum_file()  { shasum < "$1" | awk '{print $1}'; }

# The checksum that actually carries the "prior content survived" claim: every line
# OUTSIDE the fence, markers excluded. Fence content may change freely; this may not.
sum_outside_fence() {
  awk -v b="$AG_BEGIN" -v e="$AG_END" '
    $0 == b { inb = 1; next }
    $0 == e { inb = 0; next }
    !inb    { print }
  ' "$1" | shasum | awk '{print $1}'
}

# Raw byte-prefix checksum — the strictest form of "byte-identical", used where the
# prior file already ended in a newline and must therefore be an exact prefix.
sum_prefix() { head -c "$2" "$1" | shasum | awk '{print $1}'; }

count_line() { grep -Fxc "$1" "$2" 2>/dev/null || true; }

echo "════════════════════════════════════════════════════════════════"
echo "hmd init — AGENTS.md injection (fenced, idempotent, non-clobbering)"
echo "════════════════════════════════════════════════════════════════"

# ══════════════════════════════════════════════════════════════════════════════
# 1. CREATE — a repo with NO AGENTS.md gets one, with exactly one fenced block
# ══════════════════════════════════════════════════════════════════════════════
R1="$WORK/r1"; newrepo "$R1"
[ -f "$R1/AGENTS.md" ] && bad "1 fixture is dirty — AGENTS.md existed before init"
runinit "$R1"
A1="$R1/AGENTS.md"
if [ -f "$A1" ]; then ok "1a AGENTS.md created in a repo that had none"; else bad "1a init did not create AGENTS.md"; fi
[ "$(count_line "$AG_BEGIN" "$A1")" = "1" ] && [ "$(count_line "$AG_END" "$A1")" = "1" ] \
  && ok "1b exactly one HEIMDALL:AGENTS fence (one BEGIN, one END)" \
  || bad "1b fence count wrong" "begin=$(count_line "$AG_BEGIN" "$A1") end=$(count_line "$AG_END" "$A1")"
# The load-bearing line. If an agent reads one sentence, it is this one.
grep -Fq 'Gates are external and falsifiable — satisfying the oracle is the only path.' "$A1" \
  && ok "1c the load-bearing line is present: gates are external and falsifiable" \
  || bad "1c the oracle-is-the-only-path line is missing from the block"
grep -Fq 'hmd verdict' "$A1" && grep -Fq 'hmd demo' "$A1" \
  && ok "1d the block documents hmd verdict + hmd demo" || bad "1d verdict/demo usage missing"
grep -Fq 'deny' "$A1" && grep -Fq 'BIFRÖST' "$A1" \
  && ok "1e the block documents deny semantics (a deny blocks the commit, BIFRÖST on stderr)" \
  || bad "1e deny semantics missing"
# Short enough to be read, not skimmed past.
A1_LINES="$(wc -l < "$A1" | tr -d ' ')"
[ "$A1_LINES" -le 40 ] && ok "1f the injected block is short ($A1_LINES lines) — read at session start, not skimmed" \
  || bad "1f the block is a wall of text ($A1_LINES lines)"

# ══════════════════════════════════════════════════════════════════════════════
# 2. APPEND — a repo that ALREADY has AGENTS.md keeps every prior byte
# ══════════════════════════════════════════════════════════════════════════════
R2="$WORK/r2"; newrepo "$R2"
PRIOR="$WORK/prior-agents.md"
cat > "$PRIOR" <<'PRIOREOF'
# Acme service

House rules for agents working here.

- Run `make test` before every commit.
- Never edit `vendor/`.
- Ask before adding a dependency.

## Layout

`cmd/` is entrypoints, `internal/` is everything else.
PRIOREOF
cp "$PRIOR" "$R2/AGENTS.md"
PRIOR_BYTES="$(wc -c < "$PRIOR" | tr -d ' ')"
PRIOR_SUM="$(sum_file "$PRIOR")"
PRIOR_OUTSIDE="$(sum_outside_fence "$PRIOR")"

runinit "$R2"
A2="$R2/AGENTS.md"
[ "$(count_line "$AG_BEGIN" "$A2")" = "1" ] \
  && ok "2a the block was appended to a pre-existing AGENTS.md (exactly one fence)" \
  || bad "2a fence count wrong after append" "begin=$(count_line "$AG_BEGIN" "$A2")"
# THE assertion: a checksum of the non-fenced regions, not an eyeball diff.
GOT_OUTSIDE="$(sum_outside_fence "$A2")"
[ "$GOT_OUTSIDE" = "$PRIOR_OUTSIDE" ] \
  && ok "2b prior content is byte-identical OUTSIDE the fence (sha1 $PRIOR_OUTSIDE)" \
  || bad "2b prior content changed outside the fence" "want $PRIOR_OUTSIDE got $GOT_OUTSIDE"
# And the strictest form: the original file is an exact byte PREFIX of the result.
GOT_PREFIX="$(sum_prefix "$A2" "$PRIOR_BYTES")"
[ "$GOT_PREFIX" = "$PRIOR_SUM" ] \
  && ok "2c the original file survives as an exact byte prefix (first $PRIOR_BYTES bytes, sha1 $PRIOR_SUM)" \
  || bad "2c the first $PRIOR_BYTES bytes are not the original file" "want $PRIOR_SUM got $GOT_PREFIX"
grep -Fq 'Never edit `vendor/`.' "$A2" && grep -Fq '# Acme service' "$A2" \
  && ok "2d the repo's own house rules are still there" || bad "2d prior house rules were lost"

# ══════════════════════════════════════════════════════════════════════════════
# 3. IDEMPOTENT — re-run twice; no duplication, no drift
# ══════════════════════════════════════════════════════════════════════════════
A1_RUN1="$(sum_file "$A1")"; A2_RUN1="$(sum_file "$A2")"
runinit "$R1"; runinit "$R2"
A1_RUN2="$(sum_file "$A1")"; A2_RUN2="$(sum_file "$A2")"
runinit "$R1"; runinit "$R2"
A1_RUN3="$(sum_file "$A1")"; A2_RUN3="$(sum_file "$A2")"

[ "$A1_RUN1" = "$A1_RUN2" ] && [ "$A1_RUN2" = "$A1_RUN3" ] \
  && ok "3a created AGENTS.md does not drift one byte across 3 inits (sha1 $A1_RUN1)" \
  || bad "3a created AGENTS.md drifted" "r1=$A1_RUN1 r2=$A1_RUN2 r3=$A1_RUN3"
[ "$A2_RUN1" = "$A2_RUN2" ] && [ "$A2_RUN2" = "$A2_RUN3" ] \
  && ok "3b appended AGENTS.md does not drift one byte across 3 inits (sha1 $A2_RUN1)" \
  || bad "3b appended AGENTS.md drifted" "r1=$A2_RUN1 r2=$A2_RUN2 r3=$A2_RUN3"
_dup=0
for f in "$A1" "$A2"; do
  [ "$(count_line "$AG_BEGIN" "$f")" = "1" ] || _dup=1
  [ "$(count_line "$AG_END"   "$f")" = "1" ] || _dup=1
done
[ "$_dup" = 0 ] && ok "3c still EXACTLY one fenced block in both repos after 3 inits (no duplication)" \
  || bad "3c the fenced block duplicated across re-inits"
[ "$(sum_outside_fence "$A2")" = "$PRIOR_OUTSIDE" ] \
  && ok "3d prior content is STILL byte-identical outside the fence after 3 inits" \
  || bad "3d re-init corrupted content outside the fence"

# ══════════════════════════════════════════════════════════════════════════════
# 4. THE FENCE LINE — inside is ours and is overwritten; outside is theirs and survives
# ══════════════════════════════════════════════════════════════════════════════
# Edit INSIDE the fence (replace the load-bearing line) and OUTSIDE it (append a
# section the repo owns), then re-init.
awk -v b="$AG_BEGIN" '
  { print }
  $0 == b { print "AGENT EDIT INSIDE THE FENCE — must not survive re-init" }
' "$A2" > "$A2.tmp" && mv "$A2.tmp" "$A2"
printf '\n## Added by the repo after init\n\nThis paragraph is outside the fence and is ours.\n' >> "$A2"
OUTSIDE_AFTER_EDIT="$(sum_outside_fence "$A2")"
grep -Fq 'AGENT EDIT INSIDE THE FENCE' "$A2" || bad "4 setup failed — the in-fence edit was not planted"

runinit "$R2"
grep -Fq 'AGENT EDIT INSIDE THE FENCE' "$A2" \
  && bad "4a an edit INSIDE the fence survived re-init — the fence is not authoritative" \
  || ok "4a an edit INSIDE the fence is overwritten on re-init (that is the contract)"
grep -Fq 'This paragraph is outside the fence and is ours.' "$A2" \
  && ok "4b an edit OUTSIDE the fence SURVIVES re-init" \
  || bad "4b an edit outside the fence was destroyed"
[ "$(sum_outside_fence "$A2")" = "$OUTSIDE_AFTER_EDIT" ] \
  && ok "4c everything outside the fence is byte-identical after re-init (sha1 $OUTSIDE_AFTER_EDIT)" \
  || bad "4c content outside the fence changed" "want $OUTSIDE_AFTER_EDIT got $(sum_outside_fence "$A2")"
grep -Fq 'Gates are external and falsifiable — satisfying the oracle is the only path.' "$A2" \
  && ok "4d the block was re-rendered fresh (the load-bearing line is back)" \
  || bad "4d re-init did not restore the block"

# ══════════════════════════════════════════════════════════════════════════════
# 5. UNCLOSED FENCE — a BEGIN with no END runs to EOF, so it is REFUSED, not re-rendered
# ══════════════════════════════════════════════════════════════════════════════
R3="$WORK/r3"; newrepo "$R3"
A3="$R3/AGENTS.md"
{ printf '# Mine\n\nAbove the fence.\n'; printf '%s\n' "$AG_BEGIN"; printf '\nstale block body\n\nBelow, with the END marker deleted by a human.\n'; } > "$A3"
BROKEN_SUM="$(sum_file "$A3")"
runinit "$R3"
[ "$(sum_file "$A3")" = "$BROKEN_SUM" ] \
  && ok "5a an unclosed fence is REFUSED — the file is left exactly as it was (no lines swallowed)" \
  || bad "5a init rewrote a file with an unclosed fence" "was $BROKEN_SUM now $(sum_file "$A3")"
grep -Fq 'Below, with the END marker deleted by a human.' "$A3" \
  && ok "5b the lines after the unclosed BEGIN were NOT swallowed" \
  || bad "5b content after an unclosed BEGIN was destroyed"
[ -x "$R3/.heimdall/hooks/pre-commit" ] \
  && ok "5c a refused AGENTS.md write did NOT stop the hooks installing (they are the enforcement)" \
  || bad "5c the hooks were not installed when AGENTS.md could not be written"
ERR3="$WORK/r3.err"
( cd "$R3" && perl -e 'alarm 60; exec @ARGV' -- "$INIT_BIN" --agents-only ) >/dev/null 2>"$ERR3"; EX3=$?
[ "$EX3" != 0 ] && ok "5d --agents-only exits nonzero on an unclosed fence" || bad "5d an unclosed fence exited 0"
grep -Fq 'unclosed' "$ERR3" \
  && ok "5e the failure names the cause on stderr (actionable, never silent)" \
  || bad "5e the refusal was silent about why" "$(cat "$ERR3")"

# ══════════════════════════════════════════════════════════════════════════════
# 6. --agents-only re-renders the fence WITHOUT touching hooks or git config
# ══════════════════════════════════════════════════════════════════════════════
R4="$WORK/r4"; newrepo "$R4"
( cd "$R4" && perl -e 'alarm 60; exec @ARGV' -- "$INIT_BIN" --agents-only ) >/dev/null 2>&1
[ -f "$R4/AGENTS.md" ] && [ "$(count_line "$AG_BEGIN" "$R4/AGENTS.md")" = "1" ] \
  && ok "6a --agents-only writes the fence" || bad "6a --agents-only did not write the fence"
HP4="$(git -C "$R4" config --get core.hooksPath 2>/dev/null || true)"
[ -z "$HP4" ] && [ ! -d "$R4/.heimdall/hooks" ] \
  && ok "6b --agents-only touched NO hooks and NO git config" \
  || bad "6b --agents-only had side effects" "hooksPath='$HP4' hooksdir=$([ -d "$R4/.heimdall/hooks" ] && echo present || echo absent)"

# ══════════════════════════════════════════════════════════════════════════════
# 7. the bin parses clean
# ══════════════════════════════════════════════════════════════════════════════
bash -n "$INIT_BIN" 2>/dev/null && ok "7 bin/heimdall-init passes bash -n" || bad "7 bin/heimdall-init has a syntax error"

echo
printf "  agents-md-injection: %d passed, %d failed\n" "$PASS" "$FAIL"
[ "$FAIL" -eq 0 ] || exit 1
