#!/usr/bin/env bash
# heimdall-deploy-public-rr.test.sh — HERMETIC falsifier for deploy/cloud-run/deploy-public-rr.sh
# (the W4 public multi-tenant `rr` deploy sequencer). NO real gcloud/network/creds: the only
# external tool the SUT needs (gcloud) is a fake on PATH we control, and the secret-safe paths
# are exercised WITHOUT ever handing the script a real credential.
#
# WHAT THIS PROVES (each an independent falsifier):
#   1. --dry-run needs NO creds and prints the FULL W4 plan, in order:
#        preflight/APIs → gh-app secrets → deploy (go-live + HEIMDALL_RR_TENANT_AUTHZ=1)
#        → BYOC store → enroll token → verify. Exit 0. Zero side effects (no fake gcloud on PATH).
#   2. NO SECRET IS EVER ECHOED — a --dry-run handed a SENTINEL App id + a SENTINEL key file
#        never prints either value (the plan shows secret NAMES + redacted markers only).
#   3. SA-ACCOUNT PREFLIGHT WARNS + REFUSES — when the active gcloud account is a
#        *.gserviceaccount.com, preflight warns LOUDLY and exits nonzero (the exact footgun).
#   4. HUMAN account passes the account check (the control — no SA warning) then stops on the
#        next real gate (project describe), proving the SA branch is account-specific.
#   5. BAD ARGS rejected — an unknown flag exits 2; a real run missing --gh-app-id exits nonzero.
set -uo pipefail

SELF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$SELF_DIR/.." && pwd)"
SUT="$REPO/deploy/cloud-run/deploy-public-rr.sh"
[ -f "$SUT" ] || { echo "FATAL: SUT not found: $SUT" >&2; exit 2; }

PASS=0; FAIL=0
ok()  { PASS=$((PASS+1)); printf "  \033[32mPASS\033[0m %s\n" "$1"; }
bad() { FAIL=$((FAIL+1)); printf "  \033[31mFAIL\033[0m %s\n" "$1"; }

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

# ── a hermetic fake gcloud: answers ONLY the two preflight probes, deterministically.
#    FAKE_GCLOUD_ACCOUNT drives the active-account check; projects-describe FAILS by default so
#    a real run halts right after preflight (we never reach a mutating gcloud call). ─────────
FAKEBIN="$WORK/fakebin"
mkdir -p "$FAKEBIN"
cat > "$FAKEBIN/gcloud" <<'FAKE'
#!/usr/bin/env bash
args="$*"
case "$args" in
  *"auth list"*)         printf '%s\n' "${FAKE_GCLOUD_ACCOUNT:-}" ;;
  *"projects describe"*) exit "${FAKE_PROJECT_RC:-1}" ;;   # default: fail -> stop after preflight
  *) exit 0 ;;
esac
FAKE
chmod +x "$FAKEBIN/gcloud"

# run_sut <extra-env-KV...> -- <args...> : runs the SUT, captures combined output + rc.
# The leading K=V tokens (before the literal --) are exported for that run only.
OUT=""; RC=0
run_sut() {
  local env_kv=() ; while [ "${1:-}" != "--" ] && [ "$#" -gt 0 ]; do env_kv+=("$1"); shift; done
  shift || true   # drop the --
  OUT="$(env "${env_kv[@]}" bash "$SUT" "$@" 2>&1)"; RC=$?
}

echo "── deploy-public-rr.sh — hermetic W4 falsifier ─────────────"

# ── 1. --dry-run: no creds, full ordered plan, exit 0, no gcloud on PATH ──────────────────
# (run with a PATH that has NO fake gcloud — proves dry-run touches no external tool.)
OUT="$(PATH="/usr/bin:/bin:/usr/sbin:/sbin" bash "$SUT" --dry-run 2>&1)"; RC=$?
[ "$RC" = "0" ] && ok "dry-run exits 0 with no args/creds" || bad "dry-run exit=$RC (expected 0)"
plan_has() { printf '%s' "$OUT" | grep -qF "$1" && ok "dry-run plan: $2" || bad "dry-run plan MISSING: $2 ($1)"; }
plan_has "1. preflight"                              "preflight step present"
plan_has "services enable run.googleapis.com"        "enables run API (guarded)"
plan_has "secretmanager.googleapis.com"              "enables secretmanager API"
plan_has "artifactregistry.googleapis.com"           "enables artifactregistry API"
plan_has "iap.googleapis.com"                        "enables iap API"
plan_has "heimdall-gh-app-id"                         "gh-app id secret named"
plan_has "heimdall-gh-app-private-key"               "gh-app private-key secret named"
plan_has "go-live.sh"                                "reuses go-live.sh for the two-service deploy"
plan_has "HEIMDALL_RR_TENANT_AUTHZ=1"               "activates the multi-tenant authz gate"
plan_has "HEIMDALL_TEAM_CRED_STORE=secretmanager"    "activates the BYOC Secret-Manager store"
plan_has "cp-enroll-token"                           "mints the enroll token"
plan_has "secrets.token_urlsafe"                     "enroll token generated by python3 (piped, not argv)"
plan_has "rr setup --mode control-plane"            "prints the user onboarding command"
plan_has "/rr-task"                                  "verify probes the /rr-task route"
plan_has "no_such_route"                             "verify asserts the gated-route 404 boundary"
plan_has "6. verify"                                 "verify step present"
# ordering: preflight before deploy before verify.
if printf '%s' "$OUT" | grep -nF -e "1. preflight" -e "3. deploy" -e "6. verify" | awk -F: '{print $1}' \
     | { read -r a; read -r b; read -r c; [ "$a" -lt "$b" ] && [ "$b" -lt "$c" ]; }; then
  ok "plan order: preflight -> deploy -> verify"
else bad "plan is out of order (preflight/deploy/verify)"; fi

# ── 2. no secret is ever echoed (SENTINEL App id + SENTINEL key file, dry-run) ────────────
KEYF="$WORK/app.pem"
printf -- '-----BEGIN RSA PRIVATE KEY-----\nSENTINELKEYMATERIAL_DO_NOT_ECHO\n-----END RSA PRIVATE KEY-----\n' > "$KEYF"
OUT="$(PATH="/usr/bin:/bin" bash "$SUT" --dry-run --gh-app-id 8675309SENTINELID --gh-app-key-file "$KEYF" 2>&1)"; RC=$?
[ "$RC" = "0" ] && ok "dry-run with provided creds still exits 0" || bad "dry-run w/creds exit=$RC (expected 0)"
if printf '%s' "$OUT" | grep -q "SENTINEL"; then
  bad "SECRET LEAK — a SENTINEL value (App id or key material) appeared in the plan output"
else ok "no secret echoed — neither the App id nor the key PEM appears in the plan"; fi

# ── 3. SA-account preflight warns LOUDLY + refuses (nonzero) ───────────────────────────────
run_sut "PATH=$FAKEBIN:/usr/bin:/bin" "FAKE_GCLOUD_ACCOUNT=cp-run@heimdall-control-plane.iam.gserviceaccount.com" \
  -- --gh-app-id 123456 --gh-app-key-file "$KEYF"
if [ "$RC" != "0" ] && printf '%s' "$OUT" | grep -qi "SERVICE ACCOUNT"; then
  ok "SA active account -> loud warning + refusal (exit=$RC)"
else bad "SA active account did NOT warn+refuse (exit=$RC)"; fi
printf '%s' "$OUT" | grep -q "gserviceaccount.com" \
  && ok "SA warning names the offending *.gserviceaccount.com identity" \
  || bad "SA warning did not surface the gserviceaccount identity"

# ── 4. human account is accepted (control) — no SA warning; stops on the next gate ─────────
run_sut "PATH=$FAKEBIN:/usr/bin:/bin" "FAKE_GCLOUD_ACCOUNT=rj@superpe.co" "FAKE_PROJECT_RC=1" \
  -- --gh-app-id 123456 --gh-app-key-file "$KEYF"
if printf '%s' "$OUT" | grep -qi "SERVICE ACCOUNT"; then
  bad "human account wrongly triggered the SA warning"
else ok "human account -> no SA warning (SA branch is account-specific)"; fi
printf '%s' "$OUT" | grep -q "human — ok" \
  && ok "human account is explicitly accepted at preflight" \
  || bad "human account was not accepted at preflight"

# ── 5. bad args rejected ───────────────────────────────────────────────────────────────────
run_sut "PATH=/usr/bin:/bin" -- --bogus-flag
[ "$RC" = "2" ] && ok "unknown flag -> exit 2" || bad "unknown flag exit=$RC (expected 2)"
run_sut "PATH=/usr/bin:/bin" --   # real run, no creds
if [ "$RC" != "0" ] && printf '%s' "$OUT" | grep -q "gh-app-id"; then
  ok "real run missing --gh-app-id -> refused (exit=$RC)"
else bad "real run missing creds not refused (exit=$RC)"; fi

echo "──────────────────────────────────────────"
echo "heimdall-deploy-public-rr: $PASS passed, $FAIL failed"
[ "$FAIL" = "0" ] || exit 1
