#!/usr/bin/env bash
#
# pre-push-gate-dedup.test.sh — BEHAVIOURAL proof that a `git push` issued from
# inside Claude Code does not pay for the oracle-falsifiability + corpus-regression
# gates TWICE.
#
# WHY THIS FILE EXISTS
# ---------------------
# Two independent layers both gate a push:
#   1. hooks/hooks.json's PreToolUse `git push` chain (fires when an AGENT issues
#      `git push` through the Bash tool — Claude-Code-specific).
#   2. The native git pre-push hook, `.heimdall/hooks/pre-push`, generated by
#      `hmd init` and wired via `core.hooksPath=.heimdall/hooks`. It shells out to
#      `bin/heimdall-gate-run --phase pre-push`, which runs the SAME falsify-per-
#      domain loop and the SAME `bin/corpus run` — tool-agnostic, so a human or a
#      non-Claude-Code committer is covered too (Layer 0, "universal git core").
#
# When BOTH are wired (the common case: an agent, inside Claude Code, pushing in a
# repo where `hmd init` has run), a single `git push` paid for oracle-falsifiability
# + corpus-regression TWICE, back to back — once inline in the PreToolUse hook, once
# a few milliseconds later when the actual `git push` subprocess invoked the native
# hook. Measured against this repo's own oracle corpus: ~65s of falsify+corpus work,
# doubled to ~130s, on every agent-issued push. This is the concrete instance of
# "checks running all the time" that has an evidenced, fixable cost — see CLAUDE.md.
#
# THE FIX this file pins down: the PreToolUse chain first asks "will the native
# hook ALSO run this in a moment?" (`core.hooksPath` resolves to exactly
# `.heimdall/hooks` AND `.heimdall/hooks/pre-push` is executable). If yes, it
# defers — skips its own inline falsify/corpus and lets the native hook be the
# sole executor (loudly, on stderr, never silently). If no — e.g. a fresh
# `git worktree add` before `hmd init` has materialized `.heimdall/hooks` there,
# which is the actual state of THIS worktree at the time this test was written —
# coverage must not drop: the inline check still runs exactly as before.
#
# THE ESCAPE-HATCH INVARIANT this file also pins down: `HMD_SKIP=1` is the native
# hook's own bypass (it logs a receipt and exits 0 without ever calling
# heimdall-gate-run). Today, HMD_SKIP has NO effect on the PreToolUse layer at all
# (grep the hook: there is no HMD_SKIP check in hooks.json). If the dedup guard
# ignored that, `HMD_SKIP=1 git push` from inside Claude Code would newly skip
# BOTH layers — silently widening what HMD_SKIP bypasses. So the guard must also
# require HMD_SKIP to be unset/0 before it trusts the native hook to cover it.
#
# ISOLATION — same technique as pre-push-quality-gate-blocking.test.sh: the hook
# command is extracted verbatim from hooks/hooks.json and run through /bin/sh with
# a JSON payload on stdin. No real `git push` is ever performed. CLAUDE_PLUGIN_ROOT
# points at a throwaway plugin dir carrying ONLY fake `falsify`/`corpus` scripts
# (each just appends a line to a marker file and exits 0) plus real evals/ fixture
# scaffolding — so "did the inline gate run" is answered by "did the marker file
# get a line", not by parsing gate output.
set -u

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HOOKS_JSON="$REPO/hooks/hooks.json"

GREEN=$'\033[32m'; RED=$'\033[31m'; RESET=$'\033[0m'
pass=0; fail=0

ok()   { pass=$((pass+1)); printf '  %sPASS%s %s\n' "$GREEN" "$RESET" "$1"; }
bad()  { fail=$((fail+1)); printf '  %sFAIL%s %s\n' "$RED" "$RESET" "$1"; [ -n "${2:-}" ] && printf '        %s\n' "$2"; }

HOOK_CMD="$(jq -r '.hooks.PreToolUse[] | select(.matcher=="Bash") | .hooks[].command' "$HOOKS_JSON" 2>/dev/null)"
if [ -z "$HOOK_CMD" ]; then
  printf '%sFATAL%s could not extract Bash PreToolUse command from %s\n' "$RED" "$RESET" "$HOOKS_JSON"
  exit 1
fi

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

# A plugin root carrying fake falsify/corpus that just record "I ran" and pass.
# heimdall-state / secret-scan / heimdall-selfscan are ABSENT so those earlier
# steps in the chain self-skip via their own `[ -x ... ]` guards (same isolation
# technique as pre-push-quality-gate-blocking.test.sh) and the run reaches the
# falsify/corpus section under test.
FAKE_PLUGIN="$WORK/plugin"
mkdir -p "$FAKE_PLUGIN/bin" "$FAKE_PLUGIN/evals/oracles/demo-domain/fixtures/mutants" "$FAKE_PLUGIN/evals/corpus"

MARKERS="$WORK/markers"
mkdir -p "$MARKERS"

cat > "$FAKE_PLUGIN/bin/falsify" <<EOF
#!/usr/bin/env bash
echo "falsify \$*" >> "$MARKERS/falsify.ran"
exit 0
EOF
chmod +x "$FAKE_PLUGIN/bin/falsify"

cat > "$FAKE_PLUGIN/bin/corpus" <<EOF
#!/usr/bin/env bash
echo "corpus \$*" >> "$MARKERS/corpus.ran"
exit 0
EOF
chmod +x "$FAKE_PLUGIN/bin/corpus"

printf '{}\n' > "$FAKE_PLUGIN/evals/corpus/INDEX.json"

# run_hook <cwd> <env-prefix-assignments...> -- <command-string>  -> sets RC/OUT/ERR
run_hook() {
  local cwd="$1"; shift
  local envs=()
  while [ "$1" != "--" ]; do envs+=("$1"); shift; done
  shift
  local cmd="$1"
  local payload
  payload="$(jq -nc --arg c "$cmd" '{tool_input:{command:$c}}')"
  rm -f "$MARKERS"/*.ran
  OUT="$(cd "$cwd" && printf '%s' "$payload" | env CLAUDE_PLUGIN_ROOT="$FAKE_PLUGIN" PATH="$FAKE_PLUGIN/bin:$PATH" "${envs[@]+"${envs[@]}"}" /bin/sh -c "$HOOK_CMD" 2>"$WORK/stderr")"
  RC=$?
  ERR="$(cat "$WORK/stderr")"
}

new_repo_cwd() {  # new_repo_cwd <n> -> path, a real git repo (no commits needed)
  local d="$WORK/case$1"
  rm -rf "$d"; mkdir -p "$d"
  ( cd "$d" && git init -q && git config user.email t@t && git config user.name t )
  # The hook's APPLIES/INDEX checks are relative to CWD, not $PLUGIN (a consuming
  # repo carries its OWN evals/ mirroring the domains it cares about) — so each
  # case's cwd needs its own marker fixtures, matching demo-domain in FAKE_PLUGIN.
  mkdir -p "$d/evals/oracles/demo-domain" "$d/evals/corpus"
  printf '{}\n' > "$d/evals/corpus/INDEX.json"
  printf '%s' "$d"
}

wire_native_hook() {  # wire_native_hook <repo-dir>  -> makes core.hooksPath resolve to a real, executable pre-push
  local d="$1"
  mkdir -p "$d/.heimdall/hooks"
  printf '#!/usr/bin/env bash\nexit 0\n' > "$d/.heimdall/hooks/pre-push"
  chmod +x "$d/.heimdall/hooks/pre-push"
  ( cd "$d" && git config core.hooksPath .heimdall/hooks )
}

printf '\npre-push gate dedup — inline falsify/corpus deferred to the native hook when wired\n'
printf -- '--------------------------------------------------------------------\n'

# === CASE 1: native pre-push hook IS wired -> inline falsify/corpus must NOT run ==
C1="$(new_repo_cwd 1)"
wire_native_hook "$C1"
run_hook "$C1" -- "git push origin main"
[ "$RC" = 0 ] || bad "1 wired-native: push proceeds (exit 0)" "got exit $RC; stdout=$OUT; stderr=$ERR"
[ "$RC" = 0 ] && ok "1 wired-native: push proceeds (exit 0)"
if [ -f "$MARKERS/falsify.ran" ]; then
  bad "1a wired-native: inline falsify did NOT run" "marker present: $(cat "$MARKERS/falsify.ran")"
else
  ok "1a wired-native: inline falsify did NOT run (deferred to the native hook)"
fi
if [ -f "$MARKERS/corpus.ran" ]; then
  bad "1b wired-native: inline corpus did NOT run" "marker present: $(cat "$MARKERS/corpus.ran")"
else
  ok "1b wired-native: inline corpus did NOT run (deferred to the native hook)"
fi
if grep -q 'delegated to the native pre-push hook' <<<"$ERR"; then
  ok "1c wired-native: the deferral is LOUD on stderr, not silent"
else
  bad "1c wired-native: deferral notice missing from stderr" "stderr=$ERR"
fi

# === CASE 2: native hook NOT wired (default hooksPath) -> inline must still run ==
C2="$(new_repo_cwd 2)"
run_hook "$C2" -- "git push origin main"
[ "$RC" = 0 ] || bad "2 unwired: push proceeds (exit 0)" "got exit $RC; stdout=$OUT; stderr=$ERR"
[ "$RC" = 0 ] && ok "2 unwired: push proceeds (exit 0)"
if [ -f "$MARKERS/falsify.ran" ]; then
  ok "2a unwired: inline falsify DID run (no native hook to defer to — coverage preserved)"
else
  bad "2a unwired: inline falsify did not run" "no coverage at all for this push"
fi
if [ -f "$MARKERS/corpus.ran" ]; then
  ok "2b unwired: inline corpus DID run (coverage preserved)"
else
  bad "2b unwired: inline corpus did not run" "no coverage at all for this push"
fi

# === CASE 3: hooksPath wired to something OTHER than .heimdall/hooks (e.g. the ===
# === separate `hmd guard install` identity-only hook at hooks/git) -> inline  ===
# === must still run, because THAT hook never calls heimdall-gate-run at all.  ===
C3="$(new_repo_cwd 3)"
mkdir -p "$C3/hooks/git"
printf '#!/usr/bin/env bash\nexit 0\n' > "$C3/hooks/git/pre-push"
chmod +x "$C3/hooks/git/pre-push"
( cd "$C3" && git config core.hooksPath hooks/git )
run_hook "$C3" -- "git push origin main"
if [ -f "$MARKERS/falsify.ran" ] && [ -f "$MARKERS/corpus.ran" ]; then
  ok "3 non-gate-run hooksPath: inline falsify+corpus still run (that hook never calls heimdall-gate-run)"
else
  bad "3 non-gate-run hooksPath: inline coverage wrongly skipped" "falsify.ran=$([ -f "$MARKERS/falsify.ran" ] && echo present || echo absent) corpus.ran=$([ -f "$MARKERS/corpus.ran" ] && echo present || echo absent)"
fi

# === CASE 4: HMD_SKIP=1 set, native hook wired -> inline must STILL run =========
# HMD_SKIP is the NATIVE hook's own bypass; it has never had any effect on the
# PreToolUse layer. The dedup guard must not accidentally extend HMD_SKIP's reach.
C4="$(new_repo_cwd 4)"
wire_native_hook "$C4"
run_hook "$C4" "HMD_SKIP=1" -- "git push origin main"
if [ -f "$MARKERS/falsify.ran" ] && [ -f "$MARKERS/corpus.ran" ]; then
  ok "4 HMD_SKIP=1 + wired-native: inline falsify+corpus still run (HMD_SKIP does not reach this layer)"
else
  bad "4 HMD_SKIP=1 + wired-native: inline coverage wrongly skipped" "HMD_SKIP silently widened to cover the PreToolUse layer"
fi

# === CASE 5: structural — hooks.json stays valid JSON ========================
if jq . "$HOOKS_JSON" >/dev/null 2>&1; then
  ok "5 hooks.json is valid JSON"
else
  bad "5 hooks.json is valid JSON" "jq failed to parse"
fi

# === CASE 6: non-push commands are never affected by the guard ================
C6="$(new_repo_cwd 6)"
wire_native_hook "$C6"
run_hook "$C6" -- "ls -la"
[ "$RC" = 0 ] && ok "6 non-push command unaffected (exit 0)" || bad "6 non-push command unaffected" "got exit $RC"

printf -- '--------------------------------------------------------------------\n'
printf '  %d passed, %d failed\n\n' "$pass" "$fail"
[ "$fail" -eq 0 ] || exit 1
