#!/usr/bin/env bash
#
# wrap-lifecycle.test.sh — §7 `hmd wrap` / `hmd unwrap`: one command to put ANY
# coding tool behind the Heimdall gate, and one command to take it back out.
#
# WHAT THIS GATES.
#   `hmd wrap <tool>` is a single command that must: install the Layer-0 git hooks,
#   write/append the AGENTS.md fenced block, start presence, and launch the tool
#   already configured. `hmd unwrap <tool>` must reverse EVERY one of those changes.
#
#   The load-bearing claim is REVERSIBILITY, and the only honest proof of it is a
#   CHECKSUM: the tree (worktree + the parts of .git wrap can reach) is summed
#   before wrap and after unwrap, and the two sums must be equal. Any residue —
#   a leftover hook, a surviving AGENTS.md fence, an extra .gitignore line, an
#   empty .heimdall/wrap dir, a stale core.hooksPath — moves the sum and this
#   gate goes RED. Eyeballing a diff is not a substitute; a checksum cannot be
#   talked out of noticing a leftover byte.
#
# THE FAILURE MODES THIS EXISTS TO CATCH (each is a real hazard already hit here):
#   · WELDED APPEND. bin/heimdall-init once appended to .gitignore with a bare `>>`,
#     concatenating its first pattern onto a file with no trailing newline and
#     destroying the dev's own rule (test/init-gitignore-append.test.sh). Anything
#     wrap appends to inherits that hazard, so the same wall is held here.
#   · CLOBBERED PRIOR STATE. A repo's own AGENTS.md, its own git hooks and its own
#     core.hooksPath predate us. Wrap may add beside them; it may never overwrite
#     them, and unwrap must hand every byte back.
#   · SHIM FORK LOOP. `--always` installs a PATH shim named after the tool. A shim
#     that re-resolves the tool through PATH finds ITSELF and forks forever. It must
#     exec the real binary by ABSOLUTE path and refuse re-entry outright.
#   · SHIM BREAKS AUTOMATION. A shim that wraps non-interactive invocations (CI,
#     scripts, `-p` pipes) breaks every pipeline the dev owns. Those must pass
#     through byte-for-byte untouched.
#   · SHIM EATS SELF-UPDATE. A shim installed where the tool writes its own binary
#     is destroyed by (or destroys) the tool's next self-update. It must not live
#     in the tool's own directory.
#   · EMPTY vs UNKNOWN COLLAPSE. Bare `hmd` must wrap-and-launch the default tool;
#     an UNKNOWN token must still fall through to the Claude task prompt (that is
#     why `hmd fix the login bug` works — test/heimdall-cli-routing.test.sh §8).
#     These are two DIFFERENT behaviours and each is asserted separately here; a
#     change that collapses them into one goes RED on the other.
#
# SAFETY. Every case runs inside a throwaway `mktemp -d` with HOME, HEIMDALL_HOME
# and the git repo all redirected into it. Nothing here can reach the real
# ~/.heimdall (live team secret + PKI), the real ~/.claude, or the real repo.
# Presence is stubbed to a recorder, so no keeper process is ever spawned.
#
# Usage:  bash test/wrap-lifecycle.test.sh
set -uo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$HERE/.." && pwd)"
BIN="$ROOT/bin"

# DEFAULT-ON egress guard: wrap shells the real presence/init plumbing. Pin the
# baked-in default at a dead port so an un-pinned call can never reach prod.
. "$ROOT/test/lib/net-default-guard.sh"

command -v git    >/dev/null 2>&1 || { echo "FATAL: git not found"    >&2; exit 2; }
command -v shasum >/dev/null 2>&1 || { echo "FATAL: shasum not found" >&2; exit 2; }

PASS=0; FAIL=0; SKIP=0
ok()   { PASS=$((PASS+1)); printf '  \033[32mPASS\033[0m %s\n' "$1"; }
bad()  { FAIL=$((FAIL+1)); printf '  \033[31mFAIL\033[0m %s\n' "$1"; [ $# -gt 1 ] && printf '       %s\n' "$2"; return 0; }
skip() { SKIP=$((SKIP+1)); printf '  \033[33mSKIP\033[0m %s\n' "$1"; }

WORK="$(mktemp -d "${TMPDIR:-/tmp}/hmd-wrap.XXXXXX")"
cleanup() { rm -rf "$WORK" 2>/dev/null || true; }
trap cleanup EXIT

# The five tools §7 names. Pinned here rather than read out of the implementation:
# a test that derives its contract from the code under test cannot notice the
# contract changing.
TOOLS="claude cursor codex gemini aider"

# The AGENTS.md fence, likewise pinned (same markers bin/heimdall-init owns).
AG_BEGIN='<!-- HEIMDALL:AGENTS:BEGIN — generated by `hmd init`; edits inside this fence are overwritten on re-init -->'
AG_END='<!-- HEIMDALL:AGENTS:END -->'

echo "hmd wrap / unwrap — §7 lifecycle    repo=$ROOT"
echo "===================================================================="

# ══════════════════════════════════════════════════════════════════════════════
# HARNESS
#
# A FAKE PLUGIN DIR holding a full copy of bin/, so PLUGIN_DIR (resolved by
# readlink -f on the copy) points at the sandbox. The real heimdall, heimdall-wrap
# and heimdall-init run; only the outward-reaching bins are replaced by recorders.
# ══════════════════════════════════════════════════════════════════════════════
FAKE="$WORK/plugin"
mkdir -p "$FAKE"
cp -R "$BIN" "$FAKE/bin"
mkdir -p "$FAKE/.claude-plugin"

STUB_OUT="$WORK/stub.log"
: > "$STUB_OUT"

# make_stub NAME — replace a bin with a recorder that logs its argv.
make_stub() {
  local name="$1"
  cat > "$FAKE/bin/$name" <<'EOSTUB'
#!/usr/bin/env bash
printf '%s ARGS: %s\n' "$(basename "$0")" "$*" >> "${HMD_STUB_OUT:-/dev/null}"
exit 0
EOSTUB
  chmod +x "$FAKE/bin/$name"
}

# Presence, team and telemetry must never leave the sandbox.
make_stub heimdall-presence
make_stub heimdall-team
make_stub heimdall-funnel
make_stub heimdall-telemetry

HWRAP="$FAKE/bin/heimdall-wrap"
HMD="$FAKE/bin/heimdall"

# FAKE TOOL BINARIES — every one of the five tools, so the launch path is really
# exercised for each rather than only for whatever happens to be installed here.
TOOLBIN="$WORK/toolbin"
mkdir -p "$TOOLBIN"
for t in $TOOLS; do
  cat > "$TOOLBIN/$t" <<'EOTOOL'
#!/usr/bin/env bash
printf 'TOOL %s ARGS: %s\n' "$(basename "$0")" "$*" >> "${HMD_TOOL_OUT:-/dev/null}"
# The launched tool also reports whether the one-hop re-entry marker reached it.
# Deliberately NOT prefixed "TOOL <name>" — 4e counts lines matching that exact
# string, and a second matching line per launch would silently double the count.
printf 'WRAPMARK %s: %s\n' "$(basename "$0")" "${HEIMDALL_WRAP_LAUNCHED:-unset}" >> "${HMD_TOOL_OUT:-/dev/null}"
exit 0
EOTOOL
  chmod +x "$TOOLBIN/$t"
done
TOOL_OUT="$WORK/tool.log"
: > "$TOOL_OUT"

# new_repo NAME — a throwaway git repo. Echoes its path.
new_repo() {
  local d="$WORK/repos/$1"
  mkdir -p "$d"
  git init -q "$d" 2>/dev/null || return 1
  git -C "$d" config user.email heimdall-test@example.invalid
  git -C "$d" config user.name  "heimdall test"
  printf '%s' "$d"
}

# run_wrap REPO ARGS… — heimdall-wrap inside REPO with a fully sandboxed env.
# `timeout(1)` does not exist on macOS, hence perl's alarm.
run_wrap() {
  local d="$1"; shift
  ( cd "$d" && \
    env -u HEIMDALL_WRAP_LAUNCHED \
    HOME="$WORK/fakehome" \
    HEIMDALL_HOME="$WORK/fakehome/.heimdall" \
    PATH="$TOOLBIN:$PATH" \
    HMD_STUB_OUT="$STUB_OUT" \
    HMD_TOOL_OUT="$TOOL_OUT" \
    HEIMDALL_NO_UPDATE_CHECK=1 \
    HEIMDALL_NO_INTRO=1 \
    HEIMDALL_NO_TEAM_AUTOSHARE=1 \
    HMD_AUTO_TEAM_DISABLE=1 \
    SHELL=/bin/zsh \
    HEIMDALL_CP_URL="http://127.0.0.1:1" \
    perl -e 'alarm 120; exec @ARGV or exit 127' -- "$HWRAP" "$@" ) >/dev/null 2>&1
}

# run_wrap_v — same, but keeps stdout/stderr for message assertions.
run_wrap_v() {
  local d="$1"; shift
  ( cd "$d" && \
    env -u HEIMDALL_WRAP_LAUNCHED \
    HOME="$WORK/fakehome" \
    HEIMDALL_HOME="$WORK/fakehome/.heimdall" \
    PATH="$TOOLBIN:$PATH" \
    HMD_STUB_OUT="$STUB_OUT" \
    HMD_TOOL_OUT="$TOOL_OUT" \
    HEIMDALL_NO_UPDATE_CHECK=1 \
    HEIMDALL_NO_INTRO=1 \
    HEIMDALL_NO_TEAM_AUTOSHARE=1 \
    HMD_AUTO_TEAM_DISABLE=1 \
    SHELL=/bin/zsh \
    HEIMDALL_CP_URL="http://127.0.0.1:1" \
    perl -e 'alarm 120; exec @ARGV or exit 127' -- "$HWRAP" "$@" ) 2>&1
}

# tree_sum DIR — one checksum over every path AND every file body in DIR.
# Directory NAMES are summed too, so an empty leftover directory is residue that
# moves the sum. Inside .git only what wrap can reach is summed (config + hooks);
# the object/ref/log stores are git's own churn and are pruned.
tree_sum() {
  local d="$1"
  ( cd "$d" 2>/dev/null || return 1
    find . -path './.git' -prune -o -print 2>/dev/null | LC_ALL=C sort
    find .git/config .git/hooks -print 2>/dev/null | LC_ALL=C sort
    { find . -path './.git' -prune -o -type f -print 2>/dev/null
      find .git/config .git/hooks -type f -print 2>/dev/null
    } | LC_ALL=C sort | tr '\n' '\0' | xargs -0 shasum 2>/dev/null
  ) | shasum | awk '{print $1}'
}

# git_cfg REPO KEY — the configured value, or the literal <unset>.
git_cfg() { git -C "$1" config --get "$2" 2>/dev/null || printf '<unset>'; }

# ══════════════════════════════════════════════════════════════════════════════
# 1. ROUND TRIP — wrap then unwrap leaves the repo byte-identical.
#    THE headline assertion. A checksum, not an eyeball.
# ══════════════════════════════════════════════════════════════════════════════
echo
echo "1. wrap → unwrap round-trip (checksum)"

R1="$(new_repo roundtrip)" || { echo "FATAL: git init failed" >&2; exit 2; }
# A repo with real content of its own, including the two files wrap appends to.
printf '# My Project\n\nHand-written.\n' > "$R1/README.md"
printf 'node_modules\n*.log\n'           > "$R1/.gitignore"
printf 'src\n'                           > "$R1/src.txt"
mkdir -p "$R1/src"
printf 'print("hi")\n'                   > "$R1/src/main.py"
git -C "$R1" add -A >/dev/null 2>&1
git -C "$R1" commit -qm "initial" >/dev/null 2>&1

BEFORE_SUM="$(tree_sum "$R1")"
BEFORE_HOOKSPATH="$(git_cfg "$R1" core.hooksPath)"

if run_wrap "$R1" wrap claude --no-launch; then
  ok "1a wrap claude exits 0"
else
  bad "1a wrap claude exited nonzero" "$(run_wrap_v "$R1" wrap claude --no-launch | tail -3)"
fi

AFTER_WRAP_SUM="$(tree_sum "$R1")"
[ "$AFTER_WRAP_SUM" != "$BEFORE_SUM" ] \
  && ok "1b wrap actually CHANGED the repo (falsifier: a no-op wrap would pass 1d for free)" \
  || bad "1b wrap changed nothing — the round-trip proof would be vacuous"

[ -f "$R1/.heimdall/hooks/pre-commit" ] \
  && ok "1c wrap installed the Layer-0 hooks" \
  || bad "1c no pre-commit hook after wrap"

grep -Fqx "$AG_BEGIN" "$R1/AGENTS.md" 2>/dev/null \
  && ok "1d wrap wrote the AGENTS.md fenced block" \
  || bad "1d AGENTS.md fence missing after wrap"

# Presence is started DETACHED by contract — a wrap must never block on a control
# plane that may be offline. So this polls for the effect rather than assuming the
# child has already been scheduled; a bounded wait is how you assert an async side
# effect without inventing a synchronous contract the product does not have.
await_stub() {
  local needle="$1" i=0
  while [ "$i" -lt 100 ]; do
    grep -q "$needle" "$STUB_OUT" 2>/dev/null && return 0
    i=$((i+1)); sleep 0.1
  done
  return 1
}
await_stub 'heimdall-presence' \
  && ok "1e wrap started presence" \
  || bad "1e presence was never started" "$(cat "$STUB_OUT")"

if run_wrap "$R1" unwrap claude; then
  ok "1f unwrap claude exits 0"
else
  bad "1f unwrap claude exited nonzero" "$(run_wrap_v "$R1" unwrap claude | tail -3)"
fi

AFTER_SUM="$(tree_sum "$R1")"
[ "$AFTER_SUM" = "$BEFORE_SUM" ] \
  && ok "1g round-trip is BYTE-IDENTICAL (sha1 $BEFORE_SUM)" \
  || bad "1g unwrap left residue" "before $BEFORE_SUM  after $AFTER_SUM"

[ "$(git_cfg "$R1" core.hooksPath)" = "$BEFORE_HOOKSPATH" ] \
  && ok "1h core.hooksPath restored ($BEFORE_HOOKSPATH)" \
  || bad "1h core.hooksPath not restored" "want $BEFORE_HOOKSPATH got $(git_cfg "$R1" core.hooksPath)"

[ "$(git_cfg "$R1" heimdall.prevHooksPath)" = "<unset>" ] \
  && ok "1i heimdall.prevHooksPath removed" \
  || bad "1i heimdall.prevHooksPath survived unwrap" "$(git_cfg "$R1" heimdall.prevHooksPath)"

# ══════════════════════════════════════════════════════════════════════════════
# 2. IDEMPOTENCE — re-wrap is a refresh, not a second install.
# ══════════════════════════════════════════════════════════════════════════════
echo
echo "2. idempotence"

R2="$(new_repo idempotent)"
printf 'node_modules\n' > "$R2/.gitignore"
git -C "$R2" add -A >/dev/null 2>&1; git -C "$R2" commit -qm init >/dev/null 2>&1
B2="$(tree_sum "$R2")"

run_wrap "$R2" wrap claude --no-launch
ONE="$(tree_sum "$R2")"
run_wrap "$R2" wrap claude --no-launch
run_wrap "$R2" wrap claude --no-launch
THREE="$(tree_sum "$R2")"

[ "$ONE" = "$THREE" ] \
  && ok "2a wrap ×3 is identical to wrap ×1 (idempotent refresh)" \
  || bad "2a re-wrap changed state" "one $ONE  three $THREE"

[ "$(grep -Fxc "$AG_BEGIN" "$R2/AGENTS.md" 2>/dev/null || echo 0)" = "1" ] \
  && ok "2b exactly one AGENTS.md fence after 3 wraps (no duplication)" \
  || bad "2b the AGENTS.md fence duplicated across re-wraps"

[ "$(grep -c '^\.heimdall/verdict\.json$' "$R2/.gitignore" 2>/dev/null || echo 0)" = "1" ] \
  && ok "2c .gitignore pattern appears exactly once after 3 wraps" \
  || bad "2c .gitignore pattern duplicated" "$(cat "$R2/.gitignore")"

run_wrap "$R2" unwrap claude
[ "$(tree_sum "$R2")" = "$B2" ] \
  && ok "2d one unwrap reverses three wraps (byte-identical)" \
  || bad "2d unwrap after 3 wraps left residue"

if run_wrap "$R2" unwrap claude; then
  ok "2e unwrap on an already-unwrapped repo exits 0 (idempotent)"
else
  bad "2e second unwrap exited nonzero"
fi
[ "$(tree_sum "$R2")" = "$B2" ] \
  && ok "2f the second unwrap changed nothing" \
  || bad "2f a redundant unwrap damaged the repo"

# ══════════════════════════════════════════════════════════════════════════════
# 3. PRE-EXISTING STATE IS NEVER CLOBBERED.
#    Standing contracts: agents-md-injection (26/0), agents-md-coexist (28/0),
#    init-gitignore-append (18/0). Wrap must not weaken any of them.
# ══════════════════════════════════════════════════════════════════════════════
echo
echo "3. pre-existing hooks / AGENTS.md / .gitignore"

R3="$(new_repo preexisting)"
# The dev's own AGENTS.md, own hook, own hooksPath, own .gitignore WITHOUT a
# trailing newline (the exact shape that welds under a bare `>>`).
printf '# Our agent rules\n\nAlways run `make lint`.\n' > "$R3/AGENTS.md"
PRIOR_AGENTS_SUM="$(shasum < "$R3/AGENTS.md" | awk '{print $1}')"
printf 'node_modules'  > "$R3/.gitignore"          # NO trailing newline — deliberate
mkdir -p "$R3/myhooks"
printf '#!/bin/sh\necho mine\n' > "$R3/myhooks/pre-commit"
chmod +x "$R3/myhooks/pre-commit"
git -C "$R3" config core.hooksPath myhooks
git -C "$R3" add -A >/dev/null 2>&1; git -C "$R3" commit -qm init >/dev/null 2>&1
B3="$(tree_sum "$R3")"

run_wrap "$R3" wrap codex --no-launch

grep -Fq 'Always run `make lint`.' "$R3/AGENTS.md" \
  && ok "3a the dev's own AGENTS.md prose survives wrap" \
  || bad "3a wrap clobbered a pre-existing AGENTS.md"

grep -Fqx "$AG_BEGIN" "$R3/AGENTS.md" \
  && ok "3b the fence was APPENDED beside it" \
  || bad "3b no fence in the pre-existing AGENTS.md"

grep -qx 'node_modules' "$R3/.gitignore" \
  && ok "3c the newline-less .gitignore rule survives as a WHOLE line (no weld)" \
  || bad "3c wrap welded onto the dev's last .gitignore line" "$(cat "$R3/.gitignore")"

[ -x "$R3/myhooks/pre-commit" ] \
  && ok "3d the dev's own pre-commit hook file is untouched" \
  || bad "3d wrap destroyed a pre-existing hook"

# Compared against git's OWN view of the repo root: on macOS /var is a symlink to
# /private/var, so mktemp's path and `rev-parse --show-toplevel` are the same
# directory spelled two ways. Comparing the raw mktemp path would fail on the
# spelling, not on the behaviour.
R3_PHYS="$(git -C "$R3" rev-parse --show-toplevel 2>/dev/null)"
[ "$(git_cfg "$R3" heimdall.prevHooksPath)" = "$R3_PHYS/myhooks" ] \
  && ok "3e the prior hooksPath is recorded for chaining" \
  || bad "3e prior hooksPath not chained" "want $R3_PHYS/myhooks got $(git_cfg "$R3" heimdall.prevHooksPath)"

run_wrap "$R3" unwrap codex
[ "$(tree_sum "$R3")" = "$B3" ] \
  && ok "3f unwrap restores the pre-existing repo byte-identically" \
  || bad "3f unwrap left residue on a repo that had its own hooks/AGENTS.md"

[ "$(shasum < "$R3/AGENTS.md" | awk '{print $1}')" = "$PRIOR_AGENTS_SUM" ] \
  && ok "3g the dev's AGENTS.md is byte-identical again (sha1 $PRIOR_AGENTS_SUM)" \
  || bad "3g AGENTS.md differs after the round trip"

[ "$(git_cfg "$R3" core.hooksPath)" = "myhooks" ] \
  && ok "3h the dev's own core.hooksPath is restored, not deleted" \
  || bad "3h core.hooksPath lost" "$(git_cfg "$R3" core.hooksPath)"

# A repo that had NO AGENTS.md must not be left holding an empty one.
R3b="$(new_repo noagents)"
git -C "$R3b" commit -qm init --allow-empty >/dev/null 2>&1
B3b="$(tree_sum "$R3b")"
run_wrap "$R3b" wrap gemini --no-launch
run_wrap "$R3b" unwrap gemini
[ ! -e "$R3b/AGENTS.md" ] \
  && ok "3i a repo that had no AGENTS.md has none again after unwrap" \
  || bad "3i unwrap left an AGENTS.md behind"
[ "$(tree_sum "$R3b")" = "$B3b" ] \
  && ok "3j the no-AGENTS.md repo round-trips byte-identically" \
  || bad "3j residue in a repo that started bare"

# ══════════════════════════════════════════════════════════════════════════════
# 4. SHIM SAFETY — `--always` installs a PATH shim. Each hazard tested.
# ══════════════════════════════════════════════════════════════════════════════
echo
echo "4. shim safety (--always)"

R4="$(new_repo shim)"
git -C "$R4" commit -qm init --allow-empty >/dev/null 2>&1
run_wrap "$R4" wrap claude --always --no-launch

SHIM="$WORK/fakehome/.heimdall/shims/claude"
if [ -x "$SHIM" ]; then
  ok "4a --always installed an executable shim at ~/.heimdall/shims/claude"
else
  bad "4a no shim installed by --always" "looked for $SHIM"
fi

# The PHYSICAL path: the shim resolves symlinks at install time so it pins the file
# the tool actually is (/var → /private/var on macOS). Asserting on the physical
# spelling tests the pinning, not the symlink layout of $TMPDIR.
REAL_TOOL="$(cd "$TOOLBIN" && pwd -P)/claude"
if [ -x "$SHIM" ] && grep -Fq "$REAL_TOOL" "$SHIM"; then
  ok "4b the shim holds the real binary's ABSOLUTE path ($REAL_TOOL)"
else
  bad "4b the shim does not pin the real binary by absolute path" "$(grep -m1 HMD_REAL= "$SHIM" 2>/dev/null)"
fi
# ...and NOT by bare name: a shim that re-resolves `claude` through PATH finds
# itself. This is the falsifier for 4b — an absolute path present somewhere in the
# file would satisfy 4b even if the exec line still used the bare name.
if [ -x "$SHIM" ] && ! grep -Eq '^[[:space:]]*exec[[:space:]]+"?(claude|\$\{?HMD_TOOL)' "$SHIM"; then
  ok "4b2 no exec line resolves the tool by bare NAME (that is the fork loop)"
else
  bad "4b2 the shim execs the tool by name — it will find itself on PATH"
fi

# SELF-UPDATE SAFETY: the shim must not sit in the tool's own directory.
if [ -x "$SHIM" ] && [ "$(cd "$(dirname "$SHIM")" && pwd -P)" != "$(cd "$TOOLBIN" && pwd -P)" ]; then
  ok "4c the shim does NOT live where the tool writes itself (self-update safe)"
else
  bad "4c the shim was installed into the tool's own directory"
fi

# FORK-LOOP REFUSAL. Put the shim dir FIRST on PATH so a shim that re-resolves
# `claude` through PATH finds itself. One call must reach the real binary; the
# alarm turns a fork loop into a hard failure rather than a hung suite.
: > "$TOOL_OUT"
SHIMDIR="$(dirname "$SHIM")"
( cd "$R4" && \
  HOME="$WORK/fakehome" HEIMDALL_HOME="$WORK/fakehome/.heimdall" \
  PATH="$SHIMDIR:$TOOLBIN:$PATH" HMD_TOOL_OUT="$TOOL_OUT" HMD_STUB_OUT="$STUB_OUT" \
  HEIMDALL_NO_INTRO=1 \
  perl -e 'alarm 25; exec @ARGV or exit 127' -- "$SHIM" --version ) >/dev/null 2>&1
SHIM_RC=$?
if [ "$SHIM_RC" -ne 142 ] && [ "$SHIM_RC" -lt 124 ]; then
  ok "4d the shim terminates — no fork loop (rc $SHIM_RC)"
else
  bad "4d the shim hung or looped (rc $SHIM_RC)"
fi
CALLS="$(grep -c 'TOOL claude' "$TOOL_OUT" 2>/dev/null | tr -d ' ')"
[ "${CALLS:-0}" = "1" ] \
  && ok "4e the shim reached the real binary EXACTLY once (not 0, not N)" \
  || bad "4e real binary called $CALLS times through the shim" "$(cat "$TOOL_OUT")"

# RE-ENTRY REFUSAL. With the guard already set, the shim must pass straight
# through instead of wrapping a second time.
: > "$TOOL_OUT"; : > "$STUB_OUT"
( cd "$R4" && \
  HOME="$WORK/fakehome" HEIMDALL_HOME="$WORK/fakehome/.heimdall" \
  PATH="$SHIMDIR:$TOOLBIN:$PATH" HMD_TOOL_OUT="$TOOL_OUT" HMD_STUB_OUT="$STUB_OUT" \
  HEIMDALL_WRAP_SHIM_ACTIVE=claude \
  perl -e 'alarm 25; exec @ARGV or exit 127' -- "$SHIM" --version ) >/dev/null 2>&1
grep -q 'TOOL claude ARGS: --version' "$TOOL_OUT" \
  && ok "4f a re-entered shim execs the real binary directly (recursion refused)" \
  || bad "4f the re-entry guard did not pass through" "$(cat "$TOOL_OUT")"

# NON-INTERACTIVE PASSTHROUGH. stdin from /dev/null and stdout to a pipe is
# exactly a CI / script invocation: argv verbatim, and NO wrap side effects.
R4b="$(new_repo shimscript)"
git -C "$R4b" commit -qm init --allow-empty >/dev/null 2>&1
: > "$TOOL_OUT"
( cd "$R4b" && \
  HOME="$WORK/fakehome" HEIMDALL_HOME="$WORK/fakehome/.heimdall" \
  PATH="$SHIMDIR:$TOOLBIN:$PATH" HMD_TOOL_OUT="$TOOL_OUT" HMD_STUB_OUT="$STUB_OUT" \
  perl -e 'alarm 25; exec @ARGV or exit 127' -- "$SHIM" -p "summarise this" </dev/null ) >/dev/null 2>&1
grep -q 'TOOL claude ARGS: -p summarise this' "$TOOL_OUT" \
  && ok "4g a non-TTY invocation passes argv through VERBATIM" \
  || bad "4g non-TTY argv was altered" "$(cat "$TOOL_OUT")"
[ ! -e "$R4b/.heimdall/hooks" ] \
  && ok "4h a non-TTY invocation performs NO wrap (automation untouched)" \
  || bad "4h the shim wrapped a non-interactive invocation — this breaks CI"

# THE TTY HALF OF THE SAME PAIR. Under a real pty, a bare invocation wraps and a
# `-p` invocation still passes through. Without both halves 4g/4h could pass for
# the wrong reason (a shim that never wraps anything).
if command -v script >/dev/null 2>&1; then
  R4c="$(new_repo shimtty)"
  git -C "$R4c" commit -qm init --allow-empty >/dev/null 2>&1
  : > "$TOOL_OUT"
  ( cd "$R4c" && \
    HOME="$WORK/fakehome" HEIMDALL_HOME="$WORK/fakehome/.heimdall" \
    PATH="$SHIMDIR:$TOOLBIN:$PATH" HMD_TOOL_OUT="$TOOL_OUT" HMD_STUB_OUT="$STUB_OUT" \
    HEIMDALL_NO_INTRO=1 \
    perl -e 'alarm 60; exec @ARGV or exit 127' -- script -q /dev/null "$SHIM" ) >/dev/null 2>&1
  [ -f "$R4c/.heimdall/hooks/pre-commit" ] \
    && ok "4i under a real TTY a bare invocation DOES wrap (the shim's whole point)" \
    || bad "4i the shim never wraps even on a TTY — 4h passes vacuously"

  R4d="$(new_repo shimttyp)"
  git -C "$R4d" commit -qm init --allow-empty >/dev/null 2>&1
  ( cd "$R4d" && \
    HOME="$WORK/fakehome" HEIMDALL_HOME="$WORK/fakehome/.heimdall" \
    PATH="$SHIMDIR:$TOOLBIN:$PATH" HMD_TOOL_OUT="$TOOL_OUT" HMD_STUB_OUT="$STUB_OUT" \
    HEIMDALL_NO_INTRO=1 \
    perl -e 'alarm 60; exec @ARGV or exit 127' -- script -q /dev/null "$SHIM" -p hello ) >/dev/null 2>&1
  [ ! -e "$R4d/.heimdall/hooks" ] \
    && ok "4j even ON a TTY, -p passes through unwrapped (a pipe is automation)" \
    || bad "4j -p was wrapped on a TTY — breaks \`claude -p\` pipelines"
else
  skip "4i/4j pty half — script(1) unavailable on this box"
fi

# SHIM REMOVAL.
run_wrap "$R4" unwrap claude
[ ! -e "$SHIM" ] \
  && ok "4k unwrap removes the PATH shim" \
  || bad "4k the shim survived unwrap"

# ── the shell rc is a file wrap APPENDS to, so it inherits the weld hazard ─────
# The dev's rc predates us and outlives us: our PATH line must land as its own
# whole line even when the file ends without a newline, must appear exactly once
# however many times --always runs, and must vanish on unwrap leaving every line
# the dev wrote byte-identical.
RC="$WORK/fakehome/.zshrc"
mkdir -p "$WORK/fakehome"
printf 'export EDITOR=vim\nalias gs="git status"' > "$RC"   # NO trailing newline
RC_PRIOR_SUM="$(shasum < "$RC" | awk '{print $1}')"

R4e="$(new_repo shimrc)"
git -C "$R4e" commit -qm init --allow-empty >/dev/null 2>&1
run_wrap "$R4e" wrap codex --always --no-launch
run_wrap "$R4e" wrap codex --always --no-launch

grep -qx 'alias gs="git status"' "$RC" \
  && ok "4l the dev's last rc line survives as a WHOLE line (no weld)" \
  || bad "4l the PATH block welded onto the dev's last rc line" "$(cat "$RC")"

[ "$(grep -c '>>> heimdall wrap shim >>>' "$RC" 2>/dev/null | tr -d ' ')" = "1" ] \
  && ok "4m exactly one PATH block after two --always installs (idempotent)" \
  || bad "4m the rc PATH block duplicated" "$(cat "$RC")"

grep -Fq "$WORK/fakehome/.heimdall/shims" "$RC" 2>/dev/null \
  && ok "4n the block puts the shim dir on PATH" \
  || bad "4n the rc block does not reference the shim dir" "$(cat "$RC")"

run_wrap "$R4e" unwrap codex
grep -q 'heimdall wrap shim' "$RC" 2>/dev/null \
  && bad "4o the rc PATH block survived unwrap" "$(cat "$RC")" \
  || ok "4o unwrap removes the rc PATH block"
[ "$(shasum < "$RC" | awk '{print $1}')" = "$RC_PRIOR_SUM" ] \
  && ok "4p the dev's rc is byte-identical again (sha1 $RC_PRIOR_SUM)" \
  || bad "4p the rc differs after the round trip" "$(cat "$RC")"

# ── HEADROOM/SHIM PARITY — the persistent `--always` shim must reach the SAME
# wrap-chain hop launch_tool reaches on the one-shot path. Before this fix,
# install_shim's generated body execs the real binary directly with no headroom
# sourcing at all: `hmd wrap <tool> --always` (the exact "set up once, forget it"
# flow) never got headroom-routed on any later invocation, even though a bare
# `hmd wrap <tool>` (no --always) got it correctly every time via launch_tool.
# Fully isolated fixtures (own PATH, own fake tool, own fake headroom CLI) so
# none of this can perturb 4a-4p above.
echo
echo "4q. shim/headroom parity (--always must reach the same chain hop)"

HRQ="$WORK/headroomshim"
mkdir -p "$HRQ/toolbin"
cat > "$HRQ/toolbin/claude" <<'EOTOOL'
#!/usr/bin/env bash
printf 'ABURL: %s\n' "${ANTHROPIC_BASE_URL:-unset}" >> "${HMD_TOOL_OUT:-/dev/null}"
exit 0
EOTOOL
chmod +x "$HRQ/toolbin/claude"

# The HMD_HEADROOM_BIN test seam (bin/lib/hmd-headroom-chain.sh) plus the exact
# fake-proxy fixture shape test/headroom-wrap-chain.test.sh section 1 already
# proves in isolation: a fake CLI that dumps straight into a stdlib HTTP /health
# responder, and a receipt.json marking the module "installed".
cat > "$HRQ/fake_http_server.py" <<'PYEOF'
import sys, json, os
from http.server import BaseHTTPRequestHandler, HTTPServer
port = int(sys.argv[1])
class Handler(BaseHTTPRequestHandler):
    def log_message(self, *args):
        return None
    def do_GET(self):
        body = json.dumps({
            "service": "headroom-proxy",
            "checks": {"upstream": {"url": "https://api.anthropic.com"}},
            "config": {"pid": os.getpid()},
        }).encode("utf-8")
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)
HTTPServer(("127.0.0.1", port), Handler).serve_forever()
PYEOF
cat > "$HRQ/fake-headroom" <<EOSH
#!/usr/bin/env bash
set -uo pipefail
case "\${1:-}" in
  proxy)
    port=8787
    prev=""
    for a in "\$@"; do
      [ "\$prev" = "--port" ] && port="\$a"
      prev="\$a"
    done
    exec python3 "$HRQ/fake_http_server.py" "\$port"
    ;;
  --version) echo "headroom, version FAKE-RECORDER" ;;
  *) exit 2 ;;
esac
EOSH
chmod +x "$HRQ/fake-headroom"
mkdir -p "$HRQ/modstate/headroom"
printf '{}\n' > "$HRQ/modstate/headroom/receipt.json"
HRQ_PORT=$((22000 + ($$ % 3000)))
HRQ_TOOL_OUT="$HRQ/tool.log"

R4q="$(new_repo shimheadroom)"
git -C "$R4q" commit -qm init --allow-empty >/dev/null 2>&1
( cd "$R4q" && \
  env -u HEIMDALL_WRAP_LAUNCHED -u ANTHROPIC_BASE_URL \
  HOME="$WORK/fakehome" HEIMDALL_HOME="$WORK/fakehome/.heimdall" \
  PATH="$HRQ/toolbin:$PATH" \
  HMD_STUB_OUT="$STUB_OUT" HMD_TOOL_OUT="$TOOL_OUT" \
  HEIMDALL_NO_UPDATE_CHECK=1 HEIMDALL_NO_INTRO=1 \
  HEIMDALL_NO_TEAM_AUTOSHARE=1 HMD_AUTO_TEAM_DISABLE=1 \
  SHELL=/bin/zsh HEIMDALL_CP_URL="http://127.0.0.1:1" \
  perl -e 'alarm 120; exec @ARGV or exit 127' -- "$HWRAP" wrap claude --always --no-launch ) >/dev/null 2>&1
SHIMQ="$WORK/fakehome/.heimdall/shims/claude"
if [ ! -x "$SHIMQ" ]; then
  bad "4q0 setup: no shim installed for the parity check — the rest of 4q/4r/4s cannot run" "looked for $SHIMQ"
fi

: > "$HRQ_TOOL_OUT"
( cd "$R4q" && \
  env -u ANTHROPIC_BASE_URL \
  HOME="$WORK/fakehome" HEIMDALL_HOME="$WORK/fakehome/.heimdall" \
  PATH="$HRQ/toolbin:$PATH" \
  HMD_HEADROOM_BIN="$HRQ/fake-headroom" HMD_MODULES_STATE="$HRQ/modstate" \
  HEADROOM_PORT="$HRQ_PORT" HMD_TOOL_OUT="$HRQ_TOOL_OUT" \
  HEIMDALL_NO_INTRO=1 \
  perl -e 'alarm 30; exec @ARGV or exit 127' -- "$SHIMQ" --version ) >/dev/null 2>&1
grep -q "ABURL: http://127.0.0.1:$HRQ_PORT" "$HRQ_TOOL_OUT" 2>/dev/null \
  && ok "4q the --always shim routes ANTHROPIC_BASE_URL through headroom, same as launch_tool" \
  || bad "4q the shim did not export ANTHROPIC_BASE_URL — it bypasses the headroom chain" "$(cat "$HRQ_TOOL_OUT" 2>/dev/null)"

# Opt-out must still be honoured from inside the shim (inherited from
# hmd_headroom_chain -> hmd_headroom_opted_out, never re-implemented locally).
: > "$HRQ_TOOL_OUT"
( cd "$R4q" && \
  env -u ANTHROPIC_BASE_URL \
  HOME="$WORK/fakehome" HEIMDALL_HOME="$WORK/fakehome/.heimdall" \
  PATH="$HRQ/toolbin:$PATH" \
  HMD_HEADROOM_BIN="$HRQ/fake-headroom" HMD_MODULES_STATE="$HRQ/modstate" \
  HEADROOM_PORT="$HRQ_PORT" HMD_TOOL_OUT="$HRQ_TOOL_OUT" \
  HMD_HEADROOM_DISABLE=1 \
  HEIMDALL_NO_INTRO=1 \
  perl -e 'alarm 30; exec @ARGV or exit 127' -- "$SHIMQ" --version ) >/dev/null 2>&1
grep -q "ABURL: unset" "$HRQ_TOOL_OUT" 2>/dev/null \
  && ok "4r HMD_HEADROOM_DISABLE=1 is honoured through the shim (opt-out inherited, not bypassed)" \
  || bad "4r opt-out was not honoured through the shim" "$(cat "$HRQ_TOOL_OUT" 2>/dev/null)"

# The dominant case TODAY: headroom module not installed. Must still exec cleanly
# (fail-open) with nothing exported — the no-op path measured at ~0.00s added.
: > "$HRQ_TOOL_OUT"
( cd "$R4q" && \
  env -u ANTHROPIC_BASE_URL \
  HOME="$WORK/fakehome" HEIMDALL_HOME="$WORK/fakehome/.heimdall" \
  PATH="$HRQ/toolbin:$PATH" \
  HMD_TOOL_OUT="$HRQ_TOOL_OUT" \
  HEIMDALL_NO_INTRO=1 \
  perl -e 'alarm 30; exec @ARGV or exit 127' -- "$SHIMQ" --version ) >/dev/null 2>&1
grep -q "ABURL: unset" "$HRQ_TOOL_OUT" 2>/dev/null \
  && ok "4s headroom-absent stays fail-open through the shim (no export, tool still runs)" \
  || bad "4s the absent-module case broke or wrongly exported a base URL" "$(cat "$HRQ_TOOL_OUT" 2>/dev/null)"

# ══════════════════════════════════════════════════════════════════════════════
# 5. DEFAULT RESOLUTION — config → detection → asked once, remembered.
# ══════════════════════════════════════════════════════════════════════════════
echo
echo "5. default tool resolution"

R5="$(new_repo defaults)"
git -C "$R5" commit -qm init --allow-empty >/dev/null 2>&1

OUT5="$(run_wrap_v "$R5" default)"
grep -qE '^(claude|cursor|codex|gemini|aider)$' <<<"$OUT5" \
  && ok "5a \`wrap default\` resolves a tool with no config (detection): $OUT5" \
  || bad "5a default resolution produced no tool" "$OUT5"

run_wrap "$R5" wrap aider --default --no-launch
[ "$(run_wrap_v "$R5" default)" = "aider" ] \
  && ok "5b --default is REMEMBERED across invocations" \
  || bad "5b --default was not persisted" "$(run_wrap_v "$R5" default)"

# Repo config must win over the user-level default.
R5b="$(new_repo defaults-repo)"
git -C "$R5b" commit -qm init --allow-empty >/dev/null 2>&1
mkdir -p "$R5b/.heimdall/wrap"
printf 'cursor\n' > "$R5b/.heimdall/wrap/default"
[ "$(run_wrap_v "$R5b" default)" = "cursor" ] \
  && ok "5c a repo-level default overrides the user-level one" \
  || bad "5c repo config did not win" "$(run_wrap_v "$R5b" default)"

# A tool that is not one of the five is refused, loudly and nonzero.
if run_wrap "$R5" wrap notatool --no-launch; then
  bad "5d an unknown tool was accepted"
else
  ok "5d an unknown tool is REFUSED (nonzero)"
fi
# Captured into a variable rather than piped into grep: this script runs under
# `pipefail`, so `run_wrap_v … | grep` inherits the PRODUCER's exit 2 (the refusal
# itself) and the assertion would read as a failure even when the match succeeds.
REFUSAL="$(run_wrap_v "$R5" wrap notatool --no-launch)"
grep -qi 'notatool' <<<"$REFUSAL" \
  && ok "5e the refusal names the offending tool" \
  || bad "5e the refusal is silent about which tool failed" "[$REFUSAL]"
grep -q 'claude cursor codex gemini aider' <<<"$REFUSAL" \
  && ok "5f the refusal lists the tools that ARE accepted" \
  || bad "5f the refusal does not say what would have worked"

# ══════════════════════════════════════════════════════════════════════════════
# 6. PER-TOOL LAUNCH SMOKE — every tool exercised against a fake binary, and the
#    REAL installed tools reported honestly (present → smoked, absent → SKIP).
# ══════════════════════════════════════════════════════════════════════════════
echo
echo "6. per-tool launch smoke"

for t in $TOOLS; do
  RT="$(new_repo "tool-$t")"
  git -C "$RT" commit -qm init --allow-empty >/dev/null 2>&1
  BT="$(tree_sum "$RT")"
  if run_wrap "$RT" wrap "$t" --no-launch; then
    ok "6.$t wrap $t succeeds"
  else
    bad "6.$t wrap $t failed" "$(run_wrap_v "$RT" wrap "$t" --no-launch | tail -3)"
  fi
  run_wrap "$RT" unwrap "$t"
  [ "$(tree_sum "$RT")" = "$BT" ] \
    && ok "6.$t wrap→unwrap round-trips byte-identically" \
    || bad "6.$t $t left residue after unwrap"
done

# The LAUNCH itself (not --no-launch): the tool binary must actually be exec'd.
R6="$(new_repo launch)"
git -C "$R6" commit -qm init --allow-empty >/dev/null 2>&1
: > "$TOOL_OUT"
run_wrap "$R6" wrap cursor
grep -q 'TOOL cursor' "$TOOL_OUT" \
  && ok "6launch wrap without --no-launch actually EXECS the tool" \
  || bad "6launch the tool was never launched" "$(cat "$TOOL_OUT")"

# ── THE ONE-HOP MARKER MUST DIE AFTER ONE HOP ────────────────────────────────
# HEIMDALL_WRAP_LAUNCHED exists to stop ONE recursion: heimdall-wrap execs
# bin/heimdall, and that heimdall must not route straight back into wrap. It is
# set as an env assignment on `exec`, so it lands in the new process image's
# environ and is inherited by EVERY descendant, for the whole life of the
# session — which turned a one-hop guard into a permanent kill switch for the
# bare-`hmd` arm. Measured before the fix: a wrapped session's `claude` was
# launched with HEIMDALL_WRAP_LAUNCHED=1, so every `hmd` typed inside it fell
# through to the task prompt instead of wrapping.
#
# Two leak paths, asserted separately because they have different causes:
#   cursor/codex/… — heimdall-wrap execs the tool DIRECTLY. No tool reads this
#                    variable, so setting it there is pure leakage.
#   claude         — heimdall-wrap execs bin/heimdall, which is the one real
#                    reader. It must CONSUME the marker so the session it goes
#                    on to launch never sees it.
grep -q 'WRAPMARK cursor: unset' "$TOOL_OUT" \
  && ok "6mark the marker does NOT leak into a directly-exec'd tool" \
  || bad "6mark heimdall-wrap leaked HEIMDALL_WRAP_LAUNCHED into cursor" \
         "$(grep WRAPMARK "$TOOL_OUT" | tr '\n' ' ')"

# The full production chain: wrap → bin/heimdall → the claude session. This is
# the launch every wrapped user actually gets.
R6c="$(new_repo launchclaude)"
git -C "$R6c" commit -qm init --allow-empty >/dev/null 2>&1
: > "$TOOL_OUT"
run_wrap "$R6c" wrap claude
# POSITIVE CONTROL first: without a real session launch in the log, the absence
# assertion below would pass by saying nothing at all.
grep -q 'TOOL claude ARGS: --agent heimdall' "$TOOL_OUT" \
  && ok "6chain the wrap→heimdall→claude chain really launched a session" \
  || bad "6chain no session launch in the log — the marker check would be vacuous" \
         "$(cat "$TOOL_OUT")"
grep -q 'WRAPMARK claude: 1' "$TOOL_OUT" \
  && bad "6chain the marker survived into the claude session — bare hmd is disarmed there" \
         "$(grep WRAPMARK "$TOOL_OUT" | tr '\n' ' ')" \
  || ok "6chain bin/heimdall CONSUMES the marker — the session inherits nothing"

for t in $TOOLS; do
  if command -v "$t" >/dev/null 2>&1; then
    RR="$(new_repo "real-$t")"
    git -C "$RR" commit -qm init --allow-empty >/dev/null 2>&1
    if ( cd "$RR" && HOME="$WORK/fakehome" HEIMDALL_HOME="$WORK/fakehome/.heimdall" \
         HMD_STUB_OUT="$STUB_OUT" HEIMDALL_NO_INTRO=1 \
         perl -e 'alarm 120; exec @ARGV or exit 127' -- "$HWRAP" wrap "$t" --no-launch ) >/dev/null 2>&1; then
      ok "6real $t is INSTALLED here and wraps against the real binary"
    else
      bad "6real $t is installed but wrap failed against the real binary"
    fi
  else
    skip "6real $t is not installed on this box — launch not smoked against the real binary"
  fi
done

# ══════════════════════════════════════════════════════════════════════════════
# 7. CLI ROUTING — `hmd wrap` / `hmd unwrap` / `hmd modules`.
# ══════════════════════════════════════════════════════════════════════════════
echo
echo "7. hmd routing"

ROUTE_DIR="$WORK/route"
mkdir -p "$ROUTE_DIR/bin" "$ROUTE_DIR/home" "$ROUTE_DIR/.claude-plugin"
cp "$BIN/heimdall" "$ROUTE_DIR/bin/heimdall"
chmod +x "$ROUTE_DIR/bin/heimdall"
touch "$ROUTE_DIR/home/setup-done"
printf '#!/usr/bin/env bash\nexit 0\n' > "$ROUTE_DIR/bin/claude"
chmod +x "$ROUTE_DIR/bin/claude"
ROUTE_OUT="$WORK/route.log"
TRACE="$WORK/trace.log"

route_stub() {
  cat > "$ROUTE_DIR/bin/$1" <<'EOR'
#!/usr/bin/env bash
printf '%s ARGS: %s\n' "$(basename "$0")" "$*" >> "${HMD_STUB_OUT:-/dev/null}"
exit 0
EOR
  chmod +x "$ROUTE_DIR/bin/$1"
}
route_stub heimdall-wrap

run_hmd() {
  : > "$ROUTE_OUT"; : > "$TRACE"
  # THE SUITE MUST CONTROL ITS OWN BASELINE. HEIMDALL_WRAP_LAUNCHED is the one-hop
  # marker heimdall-wrap sets when it re-enters bin/heimdall, and the bare-`hmd` arm
  # reads it. Anyone running this suite from INSIDE a wrapped session inherits it, and
  # every §8 assertion below would then measure the ambient session instead of the
  # dispatch — 8a/8b/8e went red for exactly that reason. `env -u` pins the precondition
  # the assertions are actually about: a bare `hmd` that is NOT already one hop from wrap.
  ( env -u HEIMDALL_WRAP_LAUNCHED \
    PATH="$ROUTE_DIR/bin:$PATH" \
    HOME="$WORK/fakehome" \
    HEIMDALL_HOME="$ROUTE_DIR/home" \
    HEIMDALL_NO_INTRO=1 HEIMDALL_NO_UPDATE_CHECK=1 \
    HMD_STUB_OUT="$ROUTE_OUT" \
    HEIMDALL_TRACE_ORDER="$TRACE" \
    perl -e 'alarm 120; exec @ARGV or exit 127' -- bash "$ROUTE_DIR/bin/heimdall" "$@" ) >/dev/null 2>&1
  return 0
}

run_hmd wrap cursor --always
grep -q 'heimdall-wrap ARGS: wrap cursor --always' "$ROUTE_OUT" \
  && ok "7a hmd wrap routes to heimdall-wrap, args verbatim" \
  || bad "7a hmd wrap did not route" "$(cat "$ROUTE_OUT")"
grep -q 'launch:task' "$TRACE" \
  && bad "7b hmd wrap fell through to the Claude launch path" \
  || ok "7b hmd wrap does NOT fall through to Claude"

run_hmd unwrap codex
grep -q 'heimdall-wrap ARGS: unwrap codex' "$ROUTE_OUT" \
  && ok "7c hmd unwrap routes to heimdall-wrap with 'unwrap' preserved" \
  || bad "7c hmd unwrap did not route" "$(cat "$ROUTE_OUT")"

# `hmd modules` → the REAL bin. Routed output must equal a direct bin/ run.
cp "$BIN/heimdall-modules" "$ROUTE_DIR/bin/heimdall-modules"
chmod +x "$ROUTE_DIR/bin/heimdall-modules"
ROUTED="$( PATH="$ROUTE_DIR/bin:$PATH" HOME="$WORK/fakehome" HEIMDALL_HOME="$ROUTE_DIR/home" \
           HEIMDALL_NO_INTRO=1 HEIMDALL_NO_UPDATE_CHECK=1 \
           perl -e 'alarm 120; exec @ARGV or exit 127' -- bash "$ROUTE_DIR/bin/heimdall" modules list --json 2>/dev/null )"
DIRECT="$( HOME="$WORK/fakehome" HEIMDALL_HOME="$ROUTE_DIR/home" \
           perl -e 'alarm 120; exec @ARGV or exit 127' -- "$ROUTE_DIR/bin/heimdall-modules" list --json 2>/dev/null )"
[ -n "$DIRECT" ] \
  && ok "7d the real heimdall-modules produced output for the comparison" \
  || bad "7d heimdall-modules produced nothing — the comparison would be vacuous"
[ "$ROUTED" = "$DIRECT" ] \
  && ok "7e \`hmd modules list --json\` is byte-identical to the direct bin run" \
  || bad "7e routed and direct runs differ" "routed=${#ROUTED}B direct=${#DIRECT}B"

for verb in list add remove update status verify; do
  RV="$( PATH="$ROUTE_DIR/bin:$PATH" HOME="$WORK/fakehome" HEIMDALL_HOME="$ROUTE_DIR/home" \
         HEIMDALL_NO_INTRO=1 HEIMDALL_NO_UPDATE_CHECK=1 \
         perl -e 'alarm 120; exec @ARGV or exit 127' -- bash "$ROUTE_DIR/bin/heimdall" modules "$verb" 2>&1 )"
  DV="$( HOME="$WORK/fakehome" HEIMDALL_HOME="$ROUTE_DIR/home" \
         perl -e 'alarm 120; exec @ARGV or exit 127' -- "$ROUTE_DIR/bin/heimdall-modules" "$verb" 2>&1 )"
  [ "$RV" = "$DV" ] \
    && ok "7f.$verb routed \`modules $verb\` matches the direct bin run" \
    || bad "7f.$verb routed/direct mismatch for '$verb'"
done

# ══════════════════════════════════════════════════════════════════════════════
# 8. EMPTY vs UNKNOWN — two DIFFERENT behaviours, each asserted on its own.
#
#    Empty  → wrap-and-launch the default tool (the §7 behaviour).
#    Unknown→ the Claude task prompt, unchanged. This is why `hmd fix the login
#             bug` works, and test/heimdall-cli-routing.test.sh §8 pins it at 51/0.
#    A change that collapses either into the other goes RED here.
# ══════════════════════════════════════════════════════════════════════════════
echo
echo "8. empty args vs unknown subcommand (distinct)"

# The routed heimdall-wrap stub records the call; the trace file records whether
# the Claude launch path was reached. The two are read independently.
run_hmd
EMPTY_STUB="$(cat "$ROUTE_OUT")"
EMPTY_TRACE="$(cat "$TRACE")"

grep -q 'heimdall-wrap ARGS: launch' <<<"$EMPTY_STUB" \
  && ok "8a EMPTY args wrap-and-launch the default tool (heimdall-wrap launch)" \
  || bad "8a bare hmd did not reach the wrap launcher" "stub=[$EMPTY_STUB]"

grep -q 'launch:task' <<<"$EMPTY_TRACE" \
  && bad "8b bare hmd fell through to the task prompt instead of wrapping" \
  || ok "8b EMPTY args do NOT take the unknown-token task path"

run_hmd "fix the login bug"
UNK_STUB="$(cat "$ROUTE_OUT")"
UNK_TRACE="$(cat "$TRACE")"

grep -q 'launch:task' <<<"$UNK_TRACE" \
  && ok "8c UNKNOWN token still falls through to the task prompt (hmd fix the login bug)" \
  || bad "8c the unknown-token fall-through broke" "trace=[$UNK_TRACE]"

grep -q 'heimdall-wrap' <<<"$UNK_STUB" \
  && bad "8d an unknown token was hijacked by the wrap launcher" "stub=[$UNK_STUB]" \
  || ok "8d UNKNOWN tokens are NOT routed to wrap"

[ "$EMPTY_STUB" != "$UNK_STUB" ] && [ "$EMPTY_TRACE" != "$UNK_TRACE" ] \
  && ok "8e empty and unknown produce DIFFERENT observable behaviour" \
  || bad "8e empty and unknown collapsed to the same path"

# A missing heimdall-wrap must never brick bare `hmd` (the class-4 landmine: a bare
# helper call under `set -euo pipefail` exits 127 and kills the whole launcher).
rm -f "$ROUTE_DIR/bin/heimdall-wrap"
run_hmd
grep -q 'launch:task' "$TRACE" \
  && ok "8f bare hmd survives a MISSING heimdall-wrap (degrades, never bricks)" \
  || bad "8f a missing heimdall-wrap bricked bare hmd" "trace=[$(cat "$TRACE")]"
route_stub heimdall-wrap

# ══════════════════════════════════════════════════════════════════════════════
# 9. SYNTAX
# ══════════════════════════════════════════════════════════════════════════════
echo
echo "9. syntax"
for f in "$BIN/heimdall" "$BIN/heimdall-wrap"; do
  if bash -n "$f" 2>/dev/null; then
    ok "9 $(basename "$f") passes bash -n"
  else
    bad "9 $(basename "$f") has syntax errors" "$(bash -n "$f" 2>&1 | head -3)"
  fi
done

# ── summary ───────────────────────────────────────────────────────────────────
echo
echo "--------------------------------------------------------------------"
printf 'wrap-lifecycle: %d passed, %d failed, %d skipped\n' "$PASS" "$FAIL" "$SKIP"
[ "$FAIL" -eq 0 ] || exit 1
