#!/usr/bin/env bash
# deploy-public-rr.sh — ONE command that stands up the PUBLIC, MULTI-TENANT `rr` control
# plane (Wave 4 / "W4"). It does NOT rebuild the two-service deploy infra — it SEQUENCES
# the existing artifacts (go-live.sh → deploy-public-surface.sh, setup-bot.sh's App model,
# cp_team_creds' Secret-Manager BYOC store, the cp-enroll-token mechanism) and adds the
# W4-specific activation on top: the multi-tenant authz gate + the /rr-task enqueue route.
#
# RUN BY THE OPERATOR (RJ) on his OWN machine with his OWN already-authenticated gcloud +
# the GitHub App HE creates. The agent never runs this. It never rebuilds deploy logic it
# does not own — go-live.sh owns the gated rebuild + public deploy + boundary verify; this
# script forwards to it, then flips on the two W4 deploy decisions:
#     HEIMDALL_RR_TENANT_AUTHZ=1     — turn ON the multi-tenant authz gate + POST /rr-task
#     HEIMDALL_TEAM_CRED_STORE=secretmanager — per-team BYOC creds land in Secret Manager
#
# SECRET DISCIPLINE (the #1 bar — mirrors deploy-arch-b.sh / setup-bot.sh / go-live.sh):
#   • No secret VALUE is ever an argv word (ps-visible), echoed, logged, or captured into a
#     shell variable this script prints. `set -x` is NEVER enabled.
#   • The App private-key PEM is STREAMED from --gh-app-key-file straight to gcloud STDIN
#     (`--data-file=-` < file) — never read into a var, never printed.
#   • The enroll token is generated by python3 and piped STRAIGHT to gcloud STDIN; the value
#     never leaves the pipe (safe to run in CI: no token is ever printed).
#
# SEQUENCED W4 (each step guarded + idempotent + re-runnable):
#   1. preflight   — gcloud present + authed as a HUMAN owner (LOUD warn if the active
#                    account is a *.gserviceaccount.com); project exists + billing; enable
#                    the required APIs (run, secretmanager, artifactregistry, iap) guarded.
#   2. gh-app      — App id + private-key PEM → Secret Manager (heimdall-gh-app-id +
#                    heimdall-gh-app-private-key, idempotent) + grant the runtime SA
#                    secretAccessor on each (per-secret IAM, least privilege).
#   3. deploy      — REUSE go-live.sh (gated rebuild → public surface) then ACTIVATE the W4
#                    env on BOTH services: HEIMDALL_RR_TENANT_AUTHZ=1 (authz gate + /rr-task)
#                    and HEIMDALL_TEAM_CRED_STORE=secretmanager (BYOC). Digest-pinned by
#                    go-live/deploy-public-surface — this script does not re-pin.
#   4. byoc        — confirm the per-team cred store selector is live + grant the runtime SA
#                    the role it needs to CREATE per-team secrets at enroll time. Each user's
#                    Claude cred lands in its OWN per-team Secret-Manager secret.
#   5. enroll      — mint the cp-enroll-token (reuse the go-live seam) so users can
#                    `rr setup --mode control-plane --enroll-token <t>`. Distribution is
#                    OUT-OF-BAND — the value is never printed (CI-safe).
#   6. verify      — public reachability (GET /healthz→/readyz 200); POST /rr-task UNSIGNED
#                    → 401/403 (the signed-enqueue chokepoint holds); a gated route (POST
#                    /dispatch) → app 404 {no_such_route} on the public surface (boundary).
#
# Usage:
#   deploy/cloud-run/deploy-public-rr.sh --gh-app-id <N> --gh-app-key-file <path.pem> \
#       [--project heimdall-cp-prod] [--region us-central1] \
#       [--endpoint <public-url>] [--enroll-open] [--dry-run]
#   --dry-run prints the WHOLE W4 plan (APIs → secrets → deploy → byoc → enroll → verify),
#             executes nothing, and needs NO creds/keys/tokens.
#   --gh-app-id + --gh-app-key-file are REQUIRED for a real run (step 2); a --dry-run needs
#             neither. --enroll-open forwards HEIMDALL_ENROLL_OPEN=1 (tokenless+bounded
#             enroll); the DEFAULT is token-gated (the viral/public phase).
set -euo pipefail

# ── defaults ─────────────────────────────────────────────────────────────────
PROJECT="heimdall-cp-prod"
REGION="us-central1"
GH_APP_ID=""
GH_APP_KEY_FILE=""
ENDPOINT=""
ENROLL_OPEN=0
DRY=0

# ── fixed W4 identifiers (env-var names + secret names + service names) ───────
RR_AUTHZ_ENV="HEIMDALL_RR_TENANT_AUTHZ"          # =1 turns ON the multi-tenant authz + /rr-task
TEAM_CRED_STORE_ENV="HEIMDALL_TEAM_CRED_STORE"   # =secretmanager selects the BYOC store
TEAM_CRED_STORE_VAL="secretmanager"
GH_APP_ID_SECRET="heimdall-gh-app-id"            # non-secret id, held as a secret for parity
GH_APP_KEY_SECRET="heimdall-gh-app-private-key"  # the App PEM (matches setup-bot.sh)
ENROLL_SECRET="cp-enroll-token"                  # the /enroll bootstrap-token verifier
GATED_SERVICE="heimdall-control-plane"
PUBLIC_SERVICE="heimdall-cp-public"
REQUIRED_APIS="run.googleapis.com secretmanager.googleapis.com artifactregistry.googleapis.com iap.googleapis.com"

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
GO_LIVE="$HERE/go-live.sh"

usage() { sed -n '/^# Usage:/,/the viral\/public phase/p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; }
while [ $# -gt 0 ]; do case "$1" in
  --gh-app-id)       GH_APP_ID="${2:?}";       shift 2 ;;
  --gh-app-key-file) GH_APP_KEY_FILE="${2:?}"; shift 2 ;;
  --project)         PROJECT="${2:?}";         shift 2 ;;
  --region)          REGION="${2:?}";          shift 2 ;;
  --endpoint)        ENDPOINT="${2:?}";        shift 2 ;;
  --enroll-open)     ENROLL_OPEN=1;            shift ;;
  --dry-run)         DRY=1;                    shift ;;
  -h|--help)         usage; exit 0 ;;
  *) echo "unknown arg: $1" >&2; usage >&2; exit 2 ;;
esac; done

RUNTIME_SA="heimdall-cp-run@${PROJECT}.iam.gserviceaccount.com"

say()  { printf '\033[36m▸ %s\033[0m\n' "$*"; }
warn() { printf '\033[33m! %s\033[0m\n' "$*" >&2; }
die()  { printf '\033[31m✗ %s\033[0m\n' "$*" >&2; exit 1; }
# run: in --dry-run print the command (NO secret is ever an argv here), else execute it.
run()  { if [ "$DRY" = 1 ]; then printf '  \033[90m$ %s\033[0m\n' "$*"; else "$@"; fi; }
# show: print a command WITHOUT running it (used to preview a secret-piping pipeline whose
# real form must never be executed with the value on argv — the value flows over stdin only).
show() { printf '  \033[90m$ %s\033[0m\n' "$*"; }

# ── arg validation (fail-closed, before any side effect) ─────────────────────
printf '%s' "$PROJECT" | grep -qE '^[a-z][a-z0-9-]{4,28}[a-z0-9]$' \
  || die "--project must be a valid GCP project id (got: $PROJECT)"
if [ "$DRY" != 1 ]; then
  [ -n "$GH_APP_ID" ]       || die "missing --gh-app-id <N> (required for a real run; step 2). Use --dry-run to preview without it."
  printf '%s' "$GH_APP_ID" | grep -qE '^[0-9]+$' || die "--gh-app-id must be numeric (the App's 'App ID'; got: $GH_APP_ID)"
  [ -n "$GH_APP_KEY_FILE" ] || die "missing --gh-app-key-file <path.pem> (required for a real run; step 2)"
  [ -f "$GH_APP_KEY_FILE" ] || die "private key file not found: $GH_APP_KEY_FILE"
fi

echo
printf '\033[1m╔═ HEIMDALL PUBLIC RR — W4 deploy (authz gate + /rr-task + BYOC) ═╗\033[0m\n'
printf '\033[1m║\033[0m project=%-20s region=%s  dry=%s\n' "$PROJECT" "$REGION" "$DRY"
printf '\033[1m║\033[0m gated=%-18s public=%s\n' "$GATED_SERVICE" "$PUBLIC_SERVICE"
printf '\033[1m║\033[0m activates: %s=1, %s=%s\n' "$RR_AUTHZ_ENV" "$TEAM_CRED_STORE_ENV" "$TEAM_CRED_STORE_VAL"
printf '\033[1m╚════════════════════════════════════════════════════════════════╝\033[0m\n'

# ════════════════════════════════════════════════════════════════════════════
# 1. PREFLIGHT — gcloud + human-owner auth + project/billing + required APIs.
# ════════════════════════════════════════════════════════════════════════════
say "1. preflight"
[ -f "$GO_LIVE" ] || { if [ "$DRY" = 1 ]; then warn "  go-live.sh not found at $GO_LIVE (dry-run: continuing to print the plan)"; else die "go-live.sh not found: $GO_LIVE (this script REUSES it for the two-service deploy)"; fi; }

if [ "$DRY" = 1 ]; then
  show "gcloud auth list --filter=status:ACTIVE --format='value(account)'   # must be a HUMAN owner, NOT *.gserviceaccount.com"
  show "gcloud projects describe ${PROJECT}   # confirm the project exists"
  show "gcloud beta billing projects describe ${PROJECT} --format='value(billingEnabled)'   # confirm billing"
  for api in $REQUIRED_APIS; do
    show "gcloud services enable ${api} --project=${PROJECT}   # idempotent (no-op if already enabled)"
  done
else
  command -v gcloud >/dev/null 2>&1 || die "missing 'gcloud' — install the Google Cloud SDK (https://cloud.google.com/sdk)"
  ACTIVE_ACCT="$(gcloud auth list --filter=status:ACTIVE --format='value(account)' 2>/dev/null | head -1)"
  [ -n "$ACTIVE_ACCT" ] || die "no ACTIVE gcloud account — run: gcloud auth login (as a HUMAN owner)"
  case "$ACTIVE_ACCT" in
    *.gserviceaccount.com)
      warn "════════════════════════════════════════════════════════════════"
      warn "  ACTIVE ACCOUNT IS A SERVICE ACCOUNT: ${ACTIVE_ACCT}"
      warn "  W4 must run as a HUMAN OWNER (this is the exact footgun that bit us)."
      warn "  A service-account identity typically lacks the project-owner grants to"
      warn "  create secrets, bind IAM, and enable APIs — and leaves no human audit"
      warn "  trail. Run: gcloud auth login  (then: gcloud config set account <you>)."
      warn "════════════════════════════════════════════════════════════════"
      die "refusing to proceed under a *.gserviceaccount.com identity — authenticate as a human owner." ;;
    "") die "could not resolve the active gcloud account." ;;
    *) say "  active account: ${ACTIVE_ACCT} (human — ok)" ;;
  esac
  gcloud projects describe "$PROJECT" >/dev/null 2>&1 \
    || die "project '${PROJECT}' not found (or no access as ${ACTIVE_ACCT}). Create it or fix --project."
  say "  project ${PROJECT} exists"
  BILL="$(gcloud beta billing projects describe "$PROJECT" --format='value(billingEnabled)' 2>/dev/null || echo "")"
  case "$BILL" in
    True|true) say "  billing enabled on ${PROJECT}" ;;
    "")        warn "  could not confirm billing (billing API/permission?). Deploy will FAIL if billing is off — verify before continuing." ;;
    *)         die "billing is NOT enabled on ${PROJECT} (billingEnabled=${BILL}). Enable it before deploying (spend gate)." ;;
  esac
  for api in $REQUIRED_APIS; do
    run gcloud services enable "$api" --project="$PROJECT"
  done
  say "  required APIs enabled: ${REQUIRED_APIS}"
fi

# ════════════════════════════════════════════════════════════════════════════
# 2. GITHUB APP CREDS → SECRET MANAGER (App id + private-key PEM; PEM via stdin).
#    Idempotent: create the secret container (|| exists), add a version, grant the
#    runtime SA secretAccessor per-secret (least privilege — not project-wide).
# ════════════════════════════════════════════════════════════════════════════
say "2. GitHub App creds → Secret Manager (id=${GH_APP_ID_SECRET}, key=${GH_APP_KEY_SECRET})"
put_app_secrets() {
  # App ID (numeric, non-secret, but held as a secret for a single wiring seam).
  run gcloud secrets create "$GH_APP_ID_SECRET" --replication-policy=automatic --project="$PROJECT" || true
  show "printf %s '<APP_ID>' | gcloud secrets versions add ${GH_APP_ID_SECRET} --data-file=- --project=${PROJECT}"
  if [ "$DRY" != 1 ]; then
    printf '%s' "$GH_APP_ID" | gcloud secrets versions add "$GH_APP_ID_SECRET" --data-file=- --project="$PROJECT" >/dev/null \
      || die "step 2: adding a version to ${GH_APP_ID_SECRET} failed."
  fi
  run gcloud secrets add-iam-policy-binding "$GH_APP_ID_SECRET" --project="$PROJECT" \
    --member="serviceAccount:${RUNTIME_SA}" --role=roles/secretmanager.secretAccessor

  # Private-key PEM — STREAMED from the file to gcloud STDIN (never argv, never printed).
  run gcloud secrets create "$GH_APP_KEY_SECRET" --replication-policy=automatic --project="$PROJECT" || true
  show "gcloud secrets versions add ${GH_APP_KEY_SECRET} --data-file=- --project=${PROJECT} < <APP_KEY_FILE.pem>"
  if [ "$DRY" != 1 ]; then
    gcloud secrets versions add "$GH_APP_KEY_SECRET" --data-file=- --project="$PROJECT" < "$GH_APP_KEY_FILE" >/dev/null \
      || die "step 2: streaming the App private key to ${GH_APP_KEY_SECRET} failed."
  fi
  run gcloud secrets add-iam-policy-binding "$GH_APP_KEY_SECRET" --project="$PROJECT" \
    --member="serviceAccount:${RUNTIME_SA}" --role=roles/secretmanager.secretAccessor
}
put_app_secrets
[ "$DRY" = 1 ] || say "  App id + private key stored; ${RUNTIME_SA} granted secretAccessor on both."
say "  the maintainer mints a FRESH 1-hour installation token PER CYCLE from these (heimdall-gh-app-token)."

# ════════════════════════════════════════════════════════════════════════════
# 3. DEPLOY — REUSE go-live.sh for the two-service (re)deploy, THEN activate the
#    W4 env on BOTH services. go-live owns the digest pin + boundary gates; this
#    script does not duplicate them — it only ADDS the two W4 deploy decisions.
# ════════════════════════════════════════════════════════════════════════════
say "3. deploy — go-live.sh (gated rebuild → public surface), then activate W4 env"
GL_MODE="guided"; [ "$DRY" = 1 ] && GL_MODE="--plan"
ENROLL_OPEN_FWD=0; [ "$ENROLL_OPEN" = 1 ] && ENROLL_OPEN_FWD=1
show "ENROLL_OPEN=${ENROLL_OPEN_FWD} PROJECT_ID=${PROJECT} REGION=${REGION} bash ${GO_LIVE} ${GL_MODE}"
if [ "$DRY" = 1 ]; then
  show "# go-live.sh --plan prints the two-service sequence (gated rebuild → SA no-dispatch → public deploy → boundary verify); runs ZERO mutating gcloud."
elif [ -f "$GO_LIVE" ]; then
  ENROLL_OPEN="$ENROLL_OPEN_FWD" PROJECT_ID="$PROJECT" REGION="$REGION" \
    bash "$GO_LIVE" \
    || die "step 3: go-live.sh failed (gated rebuild / public deploy / boundary verify). See its output above."
else
  die "step 3: go-live.sh missing — cannot (re)deploy the two-service surface."
fi

# ── W4 activation: set the authz gate + BYOC store on BOTH services (idempotent) ──
say "3b. activate W4 env on both services: ${RR_AUTHZ_ENV}=1, ${TEAM_CRED_STORE_ENV}=${TEAM_CRED_STORE_VAL}"
W4_ENV="${RR_AUTHZ_ENV}=1,${TEAM_CRED_STORE_ENV}=${TEAM_CRED_STORE_VAL}"
for svc in "$GATED_SERVICE" "$PUBLIC_SERVICE"; do
  run gcloud run services update "$svc" --region="$REGION" --project="$PROJECT" \
    --update-env-vars="$W4_ENV"
done
say "  ${RR_AUTHZ_ENV}=1 turns ON the multi-tenant authz gate + POST /rr-task (public enqueue-only, SIGNED)."
say "  the gated worker drains per-team queues + holds the per-team creds; the public surface writes rows only."

# ════════════════════════════════════════════════════════════════════════════
# 4. PER-TEAM BYOC STORE — the selector env is set (step 3b). Ensure the runtime
#    SA can CREATE per-team secrets at enroll time (cp_team_creds writes each
#    user's Claude cred into its OWN per-team Secret-Manager secret).
# ════════════════════════════════════════════════════════════════════════════
say "4. per-team BYOC store (${TEAM_CRED_STORE_ENV}=${TEAM_CRED_STORE_VAL})"
say "  cp_team_creds writes each team's Claude cred to a DEDICATED per-team secret"
say "  (id derived per (team_id, kind)); the raw secret rides Secret Manager only, never the state row."
say "  grant the runtime SA the role to CREATE + version those per-team secrets at enroll time:"
run gcloud projects add-iam-policy-binding "$PROJECT" \
  --member="serviceAccount:${RUNTIME_SA}" --role=roles/secretmanager.admin
[ "$DRY" = 1 ] || say "  ${RUNTIME_SA} can now create/version per-team BYOC secrets (project-scoped secretmanager.admin)."
warn "  NOTE: secretmanager.admin is scoped to project ${PROJECT} ONLY. If you run other secrets"
warn "  in this project that this SA must NOT manage, put the CP in its own project (recommended)."

# ════════════════════════════════════════════════════════════════════════════
# 5. ENROLL TOKEN — mint cp-enroll-token (reuse the go-live seam: python3 → stdin
#    → gcloud, value never printed). Token-gated by default (skip only in open mode).
# ════════════════════════════════════════════════════════════════════════════
say "5. enroll token (${ENROLL_SECRET})"
if [ "$ENROLL_OPEN" = 1 ]; then
  say "  --enroll-open: HEIMDALL_ENROLL_OPEN=1 (tokenless+bounded). Minting is OPTIONAL; skipping the mint."
  say "  users still enroll tokenless (the per-IP / budget / registry caps bound it in BOTH modes)."
else
  run gcloud secrets create "$ENROLL_SECRET" --replication-policy=automatic --project="$PROJECT" || true
  show "python3 -c 'import secrets,sys; sys.stdout.write(secrets.token_urlsafe(32))' | gcloud secrets versions add ${ENROLL_SECRET} --data-file=- --project=${PROJECT}"
  if [ "$DRY" != 1 ]; then
    python3 -c 'import secrets,sys; sys.stdout.write(secrets.token_urlsafe(32))' \
      | gcloud secrets versions add "$ENROLL_SECRET" --data-file=- --project="$PROJECT" >/dev/null \
      || die "step 5: minting ${ENROLL_SECRET} failed."
    say "  ${ENROLL_SECRET} version added (value never left the stdin pipe — safe in CI)."
  fi
fi
say "  DISTRIBUTE OUT-OF-BAND (this script NEVER prints the token). Read it once, hand to a user:"
show "gcloud secrets versions access latest --secret=${ENROLL_SECRET} --project=${PROJECT}   # run manually, share privately"
say "  the user then runs:"
show "rr setup --mode control-plane --endpoint ${ENDPOINT:-<public-url>} --enroll-token <t>"

# ════════════════════════════════════════════════════════════════════════════
# 6. VERIFY — public reachability + the two boundary assertions (signed-enqueue
#    chokepoint holds; gated routes 404 on the public surface).
# ════════════════════════════════════════════════════════════════════════════
say "6. verify (public reachability + boundary)"
if [ "$DRY" = 1 ]; then
  show "PUBLIC_URL=\$(gcloud run services describe ${PUBLIC_SERVICE} --region=${REGION} --project=${PROJECT} --format='value(status.url)')"
  show "curl -s -w '\\n%{http_code}' \"\${PUBLIC_URL}/healthz\"   # reachability; if GFE-404 externally, fall back to /readyz (expect 200 booted)"
  show "curl -s -w '\\n%{http_code}' -X POST \"\${PUBLIC_URL}/rr-task\" -d '{}'   # UNSIGNED → expect 401/403 (the signed-enqueue chokepoint)"
  show "curl -s -w '\\n%{http_code}' -X POST \"\${PUBLIC_URL}/dispatch\" -d '{}'   # gated route → expect app 404 {no_such_route} (boundary)"
  echo
  say "done (W4 plan)."
  warn "dry-run: nothing executed, no creds/keys/tokens used. Re-run without --dry-run to apply."
  exit 0
fi

PUBLIC_URL="$(gcloud run services describe "$PUBLIC_SERVICE" --region="$REGION" --project="$PROJECT" --format='value(status.url)' 2>/dev/null || true)"
[ -n "$PUBLIC_URL" ] || die "step 6: could not resolve the public service URL — the deploy may not be live."
say "  public URL: ${PUBLIC_URL}"

# 6.0 — reachability. Try /healthz; Cloud Run's GFE 404s an external GET /healthz before it
# reaches the container (a known quirk), so fall back to /readyz — the SAME pre-auth handler,
# reachable externally, and the stronger signal (it forces backend init + reports booted:true).
HZ="$(curl -s -o /dev/null -w '%{http_code}' "${PUBLIC_URL}/healthz" 2>/dev/null || true)"
if [ "$HZ" = "200" ]; then
  say "  ok — GET /healthz -> 200 (public surface reachable)"
else
  RZ_RAW="$(curl -s -w '\n%{http_code}' "${PUBLIC_URL}/readyz" 2>/dev/null || true)"
  RZ_CODE="$(printf '%s' "$RZ_RAW" | tail -n1)"
  RZ_BODY="$(printf '%s' "$RZ_RAW" | sed '$d')"
  [ "$RZ_CODE" = "200" ] \
    || die "step 6.0: public reachability FAILED — /healthz=${HZ}, /readyz=${RZ_CODE} (expected 200). The public surface is not live. STOP."
  printf '%s' "$RZ_BODY" | grep -q '"booted": *true' \
    || die "step 6.0: /readyz did not report booted:true — the container is not serving our app. STOP."
  say "  ok — GET /healthz=${HZ} (GFE), GET /readyz -> 200 booted (public surface reachable)"
fi

# 6.1 — the SIGNED-ENQUEUE chokepoint holds: an UNSIGNED POST /rr-task is refused (401/403)
# before any row is written. /rr-task is a real public route (it reaches the app), so a 404
# here would mean the route is not being served — that is ALSO a failure.
RT="$(curl -s -o /dev/null -w '%{http_code}' -X POST "${PUBLIC_URL}/rr-task" \
        -H 'Content-Type: application/json' -d '{}' 2>/dev/null || true)"
say "  public POST /rr-task (unsigned) -> ${RT}"
case "$RT" in
  401|403|429) say "  ok — unsigned POST /rr-task -> ${RT} (the §3 signed-enqueue chokepoint refuses it)" ;;
  404) die "step 6.1: public POST /rr-task -> 404 — the /rr-task route is NOT being served (is ${RR_AUTHZ_ENV}=1 live?). STOP." ;;
  *)   die "step 6.1: public POST /rr-task -> ${RT}, expected 401/403 — an UNSIGNED enqueue was NOT refused. STOP." ;;
esac

# 6.2 — the boundary holds: a gated route (POST /dispatch) is 404 on the public surface,
# FROM OUR APP (body {"error":"no_such_route"}), so a GFE/edge 404 can't false-green it.
DP_RAW="$(curl -s -w '\n%{http_code}' -X POST "${PUBLIC_URL}/dispatch" \
        -H 'Content-Type: application/json' -d '{}' 2>/dev/null || true)"
DP_CODE="$(printf '%s' "$DP_RAW" | tail -n1)"
DP_BODY="$(printf '%s' "$DP_RAW" | sed '$d')"
say "  public POST /dispatch -> ${DP_CODE}  ${DP_BODY}"
[ "$DP_CODE" = "404" ] \
  || die "step 6.2: public POST /dispatch -> ${DP_CODE}, expected 404 — the boundary LEAKED a gated route. STOP."
printf '%s' "$DP_BODY" | grep -q 'no_such_route' \
  || die "step 6.2: /dispatch 404 was NOT the app boundary (no 'no_such_route' body — a GFE/edge 404). UNVERIFIED. STOP."
say "  ok — public POST /dispatch -> app 404 {no_such_route} (boundary holds: gated routes do not resolve)"

echo
say "done — W4 public RR control plane is live."
say "Next: distribute the enroll token + the public URL OUT-OF-BAND (RUNBOOK §C). Users onboard with"
say "  rr setup --mode control-plane --endpoint ${PUBLIC_URL} --enroll-token <t>  ->  rr \"<task>\""
exit 0
